### ISSUE TITLE
Add a wheel for library dependencies

### ISSUE THREAD

**Issue by dazza-codes** [Toblerity/rtree#114]
Does rtree build a wheel that packages libspatialite?
- https://pythonwheels.com/

Some packages with wheels that provide binary libs:
- https://github.com/Toblerity/Shapely
  - https://github.com/Toblerity/Shapely/blob/master/build-wheels.sh
- https://github.com/Toblerity/Fiona

See also:
- https://github.com/mapbox/rasterio/blob/master/setup.py#L153
- https://github.com/mapbox/rasterio/blob/master/setup.py#L436

**Comment by hobu** [comment]
Rtree does not currently distribute wheels. We have depended on the package managers to provide libspatialindex builds for all platforms rather than taking on the burden of distributing them ourselves. Rtree would be a good candidate for a wheel given that it only depends on libspatialindex, but the burden of building and distributing wheels is significant, especially for such a low tempo library as Rtree.

I would be interested in patches that automated the creation of these artifacts with CI (Likely Azure Pipelines, which will provide OSX, Linux, and Windows build platforms). There will not be any opportunity for wheels until that part is complete.

**Comment by ocefpaf** [comment]
@darrenleeweber if you want to try to set something up check [`multibuild`](https://github.com/matthew-brett/multibuild). I never used it but it is "the standard" way to build wheels.

Another alternative would be the experimental [conda-press](https://github.com/regro/conda-press) that creates wheels out of `conda` packages. While experimental this would greatly simplify the process b/c we could leverage with the `conda-forge` package and publish both `conda` and `wheels` from a single setup.

**Comment by sgillies** [comment]
https://github.com/sgillies/shapely-wheels is what I use to make shapely wheels. It uses multibuild and would be a pretty good starting point. Like @hobu said, this project moves so slow that distro packagers aren't far behind the latest release if they are behind at all. At work, my colleagues are using the 0.8.3 Ubuntu packages.

**Comment by pauloabner** [comment]
@hobu , @sgillies 
Is there a date for a new release with MIT license? 
Currently I install rtree from pip specifing the last commit. 

`pip install git+https://github.com/Toblerity/rtree.git@5d33357c8e88f1a8344415dc15a7d2440211b281`

I'd like to install rtree using PIP and see on pip site a MIT version released. (https://pypi.org/project/Rtree/)

**Comment by SantiDu** [comment]
Using [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/), I'm able to build a [wheel](https://github.com/SantiDu/rtree/tree/master/wheelhouse) of rtree and its dependency with commit https://github.com/Toblerity/rtree/commit/0f626ddfa0159ef948bfa16da5f9005cb739089b, then the command `import rtree.index` works fine but when geopandas calls the import in sjoin, it fails with error_GetLastErrorNum.

**Comment by ocefpaf** [comment]
I would go for `cibuildwheel` it is the "standard" way and has more support. While building wheels from conda packages may seem tempting and easier there are many challenges there that are not being addressed.

**Comment by hobu** [comment]
>  I guess it's because __file__ paths are different in above two senarios. 

If we need to add some more logic to find the libspatialindex shared library under cibuildwheel scenarios, we should do it. @mikedh

**Comment by mikedh** [comment]
Agreed, I quite like cibuildwheel. I broke out the rtree library search logic in #163 to work with the packaged wheel version of libspatialindex. If you want the wheels generated in CI before we finish and get that merged (third party testing would be very helpful!) they are currently working and passing tests for Linux platforms. To get them before a release [download the 'wheels' artifact here](https://github.com/mikedh/rtree/actions/runs/216137950). It contains:
```
Rtree-0.9.4-cp27-cp27m-manylinux2010_i686.whl
Rtree-0.9.4-cp27-cp27m-manylinux2010_x86_64.whl
Rtree-0.9.4-cp27-cp27mu-manylinux2010_i686.whl
Rtree-0.9.4-cp27-cp27mu-manylinux2010_x86_64.whl
Rtree-0.9.4-cp35-cp35m-manylinux2010_i686.whl
Rtree-0.9.4-cp35-cp35m-manylinux2010_x86_64.whl
Rtree-0.9.4-cp36-cp36m-manylinux2010_i686.whl
Rtree-0.9.4-cp36-cp36m-manylinux2010_x86_64.whl
Rtree-0.9.4-cp37-cp37m-manylinux2010_i686.whl
Rtree-0.9.4-cp37-cp37m-manylinux2010_x86_64.whl
Rtree-0.9.4-cp38-cp38-manylinux2010_i686.whl
Rtree-0.9.4-cp38-cp38-manylinux2010_x86_64.whl
```

Windows and MacOS builds are still not working but hopefully I can get to them soon.

**Comment by hobu** [comment]
Please try 0.9.6 which includes libspatialindex builds in the wheels. Thanks again @mikedh
