### ISSUE TITLE
Problem with spatialindex_c.dll

### ISSUE THREAD

**Issue by NervenCid** [Toblerity/rtree#115]
When i try to import the module i get this error:

OSError: could not find or load spatialindex_c.dll

I tried with the pip and the unofficial version (https://www.lfd.uci.edu/~gohlke/pythonlibs/#rtree)

and nobody worked.

Somebody have a manual to get that dependency or build and install it on windows 10?

Thank you

**Comment by cgohlke** [comment]
> the unofficial version (https://www.lfd.uci.edu/~gohlke/pythonlibs/#rtree)

Those binaries certainly work, but they require the [Microsoft Visual C++ Redistributable for Visual Studio](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

**Comment by hobu** [comment]
I'm working on getting a new release together based on libspatialindex 1.9.1. I will try to include wheels built from https://github.com/regro/conda-press as well.

There have been some behavioral changes in libspatialindex that need to be caught up. Specifically in the nearest fetching. There may also be a bug or two that necessitates another libspatialindex release.

**Comment by Helveg** [comment]
@hobu Will this version be able to be installed from pip on Windows? Right now I can't specify rtree as a dependency and it's a major drawback, nearly unacceptable by today's standards. I can't have my users install rtree manually, we're not savages ;)

**Comment by hobu** [comment]
Please try 0.9.6 which include libspatialindex builds in wheels
