### ISSUE TITLE
Change in handling of empty stream

### ISSUE THREAD

**Issue by jorisvandenbossche** [Toblerity/rtree#122]
We noticed a change in the handling of an empty stream in the geopandas test suite (https://github.com/geopandas/geopandas/issues/1221). It doesn't seem anything critical, but still wondering if this was an accidental change or on purpose.

With rtree 0.8.3, you get a "Empty data stream given" error when passing an empty generator:

```
In [17]: sindex = rtree.index.Index((x for x in []))
---------------------------------------------------------------------------
RTreeError                                Traceback (most recent call last)
<ipython-input-17-fa5e0cb56316> in <module>
----> 1 sindex = rtree.index.Index((x for x in []))

~/miniconda3/lib/python3.7/site-packages/rtree/index.py in __init__(self, *args, **kwargs)
    262 
    263         if stream:
--> 264             self.handle = self._create_idx_from_stream(stream)
    265         else:
    266             self.handle = IndexHandle(self.properties.handle)

~/miniconda3/lib/python3.7/site-packages/rtree/index.py in _create_idx_from_stream(self, stream)
    726 
    727         stream = core.NEXTFUNC(py_next_item)
--> 728         return IndexStreamHandle(self.properties.handle, stream)
    729 
    730     def leaves(self):

~/miniconda3/lib/python3.7/site-packages/rtree/index.py in __init__(self, *args, **kwargs)
    852 
    853     def __init__(self, *args, **kwargs):
--> 854         self._ptr = self._create(*args, **kwargs)
    855 
    856     def _create(self, *args, **kwargs):

~/miniconda3/lib/python3.7/site-packages/rtree/core.py in check_void(result, func, cargs)
     27         msg = 'Error in "%s": %s' % (func.__name__, s)
     28         rt.Error_Reset()
---> 29         raise RTreeError(msg)
     30     return result
     31 

RTreeError: Error in "Index_CreateWithStream": IllegalArgumentException: RTree::BulkLoader::bulkLoadUsingSTR: Empty data stream given.
```

With 0.9.1, this seems to "work" now (it creates an index object):

```
In [22]: sindex = rtree.index.Index((x for x in []))
```

but once you try to do something with it, it gives a *"'Index' object has no attribute 'handle'"* error, which doesn't seem a very useful error message towards users:

```
In [23]: sindex.bounds 
...
~/miniconda3/envs/dev/lib/python3.7/site-packages/rtree/index.py in get_bounds(self, coordinate_interleaved)
    908             coordinate_interleaved = self.interleaved
    909         return _get_bounds(
--> 910             self.handle, core.rt.Index_GetBounds, coordinate_interleaved)
    911     bounds = property(get_bounds)
    912 

AttributeError: 'Index' object has no attribute 'handle'
```

**Comment by hobu** [comment]
This was intentional, but the test cases weren't good enough to capture what I was trying to do. There were a few user reports of not getting an exception when the stream function first runs and throws one, and I was trying to reflect that up to the user. 

We definitely shouldn't be creating a partially-constructed Index though. Maybe it would be best to revert the whole thing and leave the behavior where exceptions in the stream function get swallowed.

**Comment by jorisvandenbossche** [comment]
Also `intersection` then throws an error.

In itself, I personally would not mind allowing an empty index. But then I would expect that eg `empty_index.intersection(bounds)` also gives an empty result.

**Comment by hobu** [comment]
Reverted in #127
