### ISSUE TITLE
OSError: dlopen(libspatialindex_c.dylib, 6): image not found

### ISSUE THREAD

**Issue by bstadlbauer** [Toblerity/rtree#123]
When installing `rtree` with the following way: 

    conda create -n tmp-test python=3.6
    conda activate tmp-test
    pip install rtree

We get the following error in MacOS (10.14.6): 
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v4/8_tc4m_s7c7g8j61l732znyh0000gn/T/pip-install-or8d7_tk/rtree/setup.py", line 3, in <module>
        import rtree
      File "/private/var/folders/v4/8_tc4m_s7c7g8j61l732znyh0000gn/T/pip-install-or8d7_tk/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/private/var/folders/v4/8_tc4m_s7c7g8j61l732znyh0000gn/T/pip-install-or8d7_tk/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/private/var/folders/v4/8_tc4m_s7c7g8j61l732znyh0000gn/T/pip-install-or8d7_tk/rtree/rtree/core.py", line 107, in <module>
        rt = ctypes.CDLL(lib_name)
      File "/Users/bstadlbauer/miniconda3/envs/tmp-test/lib/python3.6/ctypes/__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: dlopen(libspatialindex_c.dylib, 6): image not found
```

and on Debian: 
```
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lswwpd_9/rtree/setup.py", line 3, in <module>
        import rtree
      File "/tmp/pip-install-lswwpd_9/rtree/rtree/__init__.py", line 1, in <module>
        from .index import Rtree
      File "/tmp/pip-install-lswwpd_9/rtree/rtree/index.py", line 6, in <module>
        from . import core
      File "/tmp/pip-install-lswwpd_9/rtree/rtree/core.py", line 107, in <module>
        rt = ctypes.CDLL(lib_name)
      File "/var/lib/jenkins/tools/miniconda3/envs/platform-python-cluster_develop_23/lib/python3.6/ctypes/__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: libspatialindex_c.so: cannot open shared object file: No such file or directory
```

On debian installing libspatialindex dev-dependecies helps: `apt install libspatialindex-dev`

**Comment by hobu** [comment]
Which version of Rtree are you using? Rtree definitely requires libspatialindex, and if Debian has the library in `libspatialindex-dev`, you'll need to install it to be able to use it.

**Comment by bstadlbauer** [comment]
We used to have `rtree==0.8.3` but since the release yesterday we are using `rtree==0.9.1`. We noticed the change as our automated Jenkins CI failed when creating the test environment with the newly released package (the old one worked seamlessly). So we have thought that it might have to do something with the new release and the change in `libspatialindex` detection. 

As an example, the following works on both debian and macos: 
```
conda create -n tmp-test python=3.6
conda activate tmp-test
pip install rtree==0.8.3
```

**Comment by hobu** [comment]
hmm, ok. There was some changes in the code ahead of the dlopen to find the library. It is likely this has some ill effects for Conda. I will try to investigate.

**Comment by bstadlbauer** [comment]
Thank you, if you have any idea where it might have happened I can try to help aswell

**Comment by maxnbk** [comment]
Same issue for us, essentially. 0.8.3 worked, 0.9.1 fails, with the same error. We can proceed no problem with 0.8.3 for now but wanted to +1 the issue.

**Comment by hobu** [comment]
> 0.8.3 worked, 0.9.1 fails, with the same error.

Can you describe your environment a little bit more?

**Comment by sgillies** [comment]
@bstadlbauer @maxnbk @hobu Ideally, one gets rtree for a conda env from a conda channel, right? Won't `conda install rtree` solve this?

**Comment by bstadlbauer** [comment]
@sgillies Yes that would technically work, however, our workflow on our CI is to create a new (temporary) testing python environment using conda (`conda create ...`) and the install the package that will be tested using `pip install .` in the packages root directory. When the package has `rtree` as a dependency, it will then be installed using pip.

@hobu When trying to recreate this on my personal machine (MacOS (10.14.6)) I just noticed that if you had `rtree` installed before using `conda` (in another environment) the problem seemed to be gone. So to have a reliable reproducible example should look something like this: 

```
conda create -n tmp-test python=3.6
conda activate tmp-test
pip install rtree --no-cache-dir
```

The environment producing the Error looks as follows (`conda` version 4.6.7); output of `conda evn export`: 

```
name: tmp-test
channels:
  - defaults
dependencies:
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py36_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1d=h1de35cc_3
  - pip=19.3.1=py36_0
  - python=3.6.9=h359304d_0
  - readline=7.0=h1de35cc_5
  - setuptools=42.0.1=py36_0
  - sqlite=3.30.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/bstadlbauer/anaconda3/envs/tmp-test
```

**Comment by hobu** [comment]
> `conda install rtree` 

This works for me in a clean environment on osx and linux.

**Comment by aldgagnon** [comment]
> Same issue for us, essentially. 0.8.3 worked, 0.9.1 fails, with the same error. We can proceed no problem with 0.8.3 for now but wanted to +1 the issue.

We are in the same boat. Installation of Rtree is failing when using the Python:3.6 Docker image, which is based off of Debian Buster. Installing the libspatialindex-dev dependencies via `apt-get install libspatialindex-dev` as a temporary step resolves the issue for us.

**Comment by hobu** [comment]
Please try master and report if the loading issue is resolved.
