### ISSUE TITLE
rtree 0.9 changes `PATH` incorrectly 

### ISSUE THREAD

**Issue by icexelloss** [Toblerity/rtree#126]
Hello,

I am a dev on https://github.com/ibis-project/ibis, recently we found this issue this rtree 0.9:

```
(ibis-env) root@a14be6873e30:/ibis# python
Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['PATH']
'/opt/conda/envs/ibis-env/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
>>> import rtree
>>> os.environ['PATH']
'/opt/conda/envs/ibis-env/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;/opt/conda/envs/ibis-env/lib'
>>> rtree.__version__
'0.9.1'
```

This seems to be a new bug in 0.9:

```
(ibis-env) root@a14be6873e30:/ibis# python
Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['PATH']
'/opt/conda/envs/ibis-env/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
>>> import rtree
>>> import os
>>> os.environ['PATH']
'/opt/conda/envs/ibis-env/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
>>> rtree.__version__
'0.8.3'
>>> 
```

The impact of this is that our CI is failing due because it can no longer create subprocess with the incorrect PATH, and we would have to ping to 0.8.3 of rtree until this is fixed. (We picked the dependency via geopandas). I wonder if folks can take a look? Much appreciated!

**Comment by hobu** [comment]
Should be fixed in https://github.com/Toblerity/rtree/pull/125 

Can you try master and see if it cures the issue for you?

**Comment by icexelloss** [comment]
Thanks much for the quick fix! Two followup questions:

- What's the reason to add envs/ibis-env/lib to `PATH`? My understanding is that `PATH` is only used for executables?
- I wonder when a 0.9.2 can be released (and I can remove the version ping from our side?)

**Comment by hobu** [comment]
> What's the reason to add envs/ibis-env/lib to PATH? My understanding is that PATH is only used for executables?

I was trying to be cute to attempt to remove a bunch of messy path munging that was going on in 0.8.x. I think I will revert back to 0.8.x's behavior however, because a lot of people have put up scaffolding around it.

0.9.2 will be released by the end of the week.

**Comment by icexelloss** [comment]
Great! Thanks again the quick fix.
