### ISSUE TITLE
`undefined symbol: Error_GetLastErrorNum` when dependabot checks dependancies

### ISSUE THREAD

**Issue by bryanculbertson** [Toblerity/rtree#135]
[Dependabot](https://dependabot.com/) stopped being able to check dependancies when rtree >0.9 is a requirement. According to their logs the failure is `undefined symbol: Error_GetLastErrorNum` when trying to pip install `rtree`.

I have filed an issue with Dependabot, but haven't heard back from them yet. Is there another fix for this other than getting Dependabot to install the latest `libspatialindex`?

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmpbs28h248build/rtree/setup.py", line 3, in <module>
    import rtree
  File "/tmp/tmpbs28h248build/rtree/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/tmp/tmpbs28h248build/rtree/rtree/index.py", line 6, in <module>
    from . import core
  File "/tmp/tmpbs28h248build/rtree/rtree/core.py", line 145, in <module>
    rt.Error_GetLastErrorNum.restype = ctypes.c_int
  File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/.pyenv/versions/3.7.5/bin/python3.7: undefined symbol: Error_GetLastErrorNum
```

**Comment by hobu** [comment]
libspatialindex_c is not installed or findable.

**Comment by hobu** [comment]
see https://github.com/Toblerity/rtree/issues/132

**Comment by bryanculbertson** [comment]
Thanks @hobu. If you have some more time to help, I would like to improve my bug report to Dependabot.

Is the issue here that `libspatialindex` was not required to pip install `rtree` 0.8, but is required to pip install rtree 0.9?

Or is the issue that rtree 0.9 requires libspatialindex `1.9.3` and doesn't work with `1.8.5`?

**Comment by hobu** [comment]
Rtree has always required libspatialindex. Rtree 0.9.3 will work with either libspatialindex 1.9.3 or 1.8.5. 

Rtree might be looking in a slightly different location or Dependabot is not specifying the need for libspatialindex if Rtree is selected. I'm not sure.
