### ISSUE TITLE
nearest picking just first item

### ISSUE THREAD

**Issue by adriangb** [Toblerity/rtree#140]
I ran into a case where my index had a large rectangle with a smaller rectangle inside. When I run `nearest` with `num_results=1` on a point inside the smaller rectangle, only 1 result is returned. Since the point is within both (verified by running `intersection`) I would expect that the distance to both items is 0, thus they are both equally near and are both returned. I also noticed that it's always the first one that was inserted into the index that is returned (I swapped the order of insertion and it did not change the result, if one were actually nearer, the result should change).

```python3
from rtree import index

point = (0, 0)
small_box = (-10, -10, 10, 10)
large_box = (-50, -50, 50, 50)

idx = index.Index()
idx.insert(0, small_box)
idx.insert(1, large_box)

print(list(idx.nearest(point, 2)))
print(list(idx.nearest(point, 1)))
print(list(idx.intersection(point)))
print("\n")

# swap order of insertion and index, this should change which one nearest returns
idx = index.Index()
idx.insert(0, large_box)
idx.insert(1, small_box)

print(list(idx.nearest(point, 2)))
print(list(idx.nearest(point, 1)))
print(list(idx.intersection(point)))
print("\n")
```
Output:
```
[0, 1]  # expected output for num_results=2
[0]      # should also be 0, 1
[0, 1]  # intersection confirms point is within both rectangles


[0, 1]  # expected output for num_results=2
[0]      # inconsistent with above result, swapping indexes should make this [1]
[0, 1]  # intersection confirms point is within both rectangles
```

**Comment by sr-murthy** [comment]
After the insertion of the large rectangle `(-50, -50, 50, 50)` it does make sense that `list(idx.nearest((0,0), 1))` will return only the smaller rectangle `(-10, -10, 10, 10)`, as it is nearest to the point `(0,0`), but it does appear as if it is returning `(-10, -10, 10, 10)` as nearest to `(0,0`) even if smaller rectangles closer to `(0,0)` are inserted.

    [84] idx.insert(2, (-5, -5, 5, 5))

    In [85]: idx.leaves()                                                                                                             
    Out[85]: [(0, [0, 1, 2], [-50.0, -50.0, 50.0, 50.0])]

    In [86]: list(idx.nearest(point, num_results=1))                                                                                  
    Out[86]: [0]

**Comment by adriangb** [comment]
I figured that maybe `(-10, -10, 10, 10)` was being returned because it is "closer", but that contradicts my second example, where the larger rectangle `(-50, -50, 50, 50)` is returned.

I would also like to point out that while there is some logic to the smaller rectangle being closer, I believe that in shapely a point inside a polygon would be considered to have a distance of 0 to the polygon, regardless of how close or far the polygon boundary lines are.

**Comment by sr-murthy** [comment]
Yes, I think `nearest` is more meaningful or useful when searching for the closest non-intersecting rectangles in the index. But the behaviour of `nearest` with intersecting rectangles should not be inconsistent as is clear in your example, and I think the documentation on how `nearest` works could be improved, e.g. what kind of distance metric is being used and how etc.

**Comment by adriangb** [comment]
Got it. And yes, it would be nice if that were documented. I was trying to figure out what distance metric it uses, but I couldn't really tell by looking at the Python source.

For what it's worth, I found the issue by expecting nearest to works something like this:
```python
from shapely.geometry import box, Point


point = Point(0, 0)
small_box = box(-10, -10, 10, 10)
large_box = box(-50, -50, 50, 50)


def nearest(index, geometry):
    min_dist = np.inf  # initialize
    min_ind = [] # initialize
    for ind_in_right, geo_in_ind in enumerate(index):
        dist = geometry.distance(geo_in_ind)
        if dist < min_dist:
            # new closest
            min_dist = dist  # reset
            min_ind = [ind_in_right]  # re-initialize
        elif dist == min_dist:
            # matching closest, extend list of closest
            min_ind.append(ind_in_right)
    
    return min_ind

print(nearest(index=[small_box, large_box], geometry=point))
```
Output:
```
[0, 1]
```

**Comment by adriangb** [comment]
I tested with `libspatialindex` directly and it does not seem to have this behavior (copied most of this from their tutorial):
```c++
#include <iostream>
#include <spatialindex/capi/sidx_api.h>
#include <spatialindex/capi/sidx_impl.h>
#include <spatialindex/capi/sidx_config.h>

using namespace std;
using namespace SpatialIndex;

// function to create a new spatial index
Index* createIndex()
{
	// create a property set with default values.
	// see utility.cc for all defaults  http://libspatialindex.github.io/doxygen/Utility_8cc_source.html#l00031
	Tools::PropertySet* ps = GetDefaults();
	Tools::Variant var;

	// set index type to R*-Tree
	var.m_varType = Tools::VT_ULONG;
	var.m_val.ulVal = RT_RTree;
	ps->setProperty("IndexType", var);

	// Set index to store in memory (default is disk)
	var.m_varType = Tools::VT_ULONG;
	var.m_val.ulVal = RT_Memory;
	ps->setProperty("IndexStorageType", var);

	// initalise index
	Index* idx = new Index(*ps);
	delete ps;

	// check index is ok
	if (!idx->index().isIndexValid())
		throw "Failed to create valid index";
	else
		cout << "created index" << endl;

	return idx;
}

// add a Point to index.
void addPoint(Index* idx,double lat,double lon, int64_t id)
{
	// create array with lat/lon points
	double coords[] = {lat, lon};

	// shapes can also have anobject associated with them but we'll leave that for the moment.
	uint8_t* pData = 0;
	uint32_t nDataLength = 0;

	// create shape
	SpatialIndex::IShape* shape = 0;
	shape = new SpatialIndex::Point(coords, 2);

	// insert into index along with the an object and an ID
	idx->index().insertData(nDataLength,pData,*shape,id);

	cout << "Point " << id << " inserted into index." << endl;

	delete shape;

}

// add a Rectangle to index.
void addRectangle(Index* idx, double minx, double miny, double maxx, double maxy, int64_t id)
{
	// create array with lat/lon points
	double plow[] = {minx, miny};
    double phigh[] = {maxx, maxy};

	// shapes can also have anobject associated with them but we'll leave that for the moment.
	uint8_t* pData = 0;
	uint32_t nDataLength = 0;

	// create shape
	SpatialIndex::IShape* shape = 0;
	shape = new SpatialIndex::Region(plow, phigh, 2);

	// insert into index along with the an object and an ID
	idx->index().insertData(nDataLength,pData,*shape,id);

	cout << "Rectangle " << id << " inserted into index." << endl;

	delete shape;

}

std::vector<SpatialIndex::IData*>* getNearest(Index* idx,double lat,double lon,double maxResults)
{
	double coords[] = {lat,lon};

	// get a visitor object and a point from which to search
	ObjVisitor* visitor = new ObjVisitor;
	// make point from lat/lon with two dimentions
	SpatialIndex::Point* r = new SpatialIndex::Point(coords, 2);

	// get nearesr maxResults shapes form index
	idx->index().nearestNeighborQuery(maxResults,*r,*visitor);

	// get count of results
	int64_t nResultCount;
	nResultCount = visitor->GetResultCount();

	// get actual results
	std::vector<SpatialIndex::IData*>& results = visitor->GetResults();
	// an empty vector that we will copt the results to
	vector<SpatialIndex::IData*>* resultsCopy = new vector<SpatialIndex::IData*>();

	// copy the Items into the newly allocated vector array
	// we need to make sure to clone the actual Item instead
	// of just the pointers, as the visitor will nuke them
	// upon destroy
	for (int64_t i = 0; i < nResultCount; ++i)
	{
		resultsCopy->push_back(dynamic_cast<SpatialIndex::IData*>(results[i]->clone()));
	}

	delete r;
	delete visitor;
	cout << "found " << nResultCount << " results." << endl;
}

int main(int argc, char* argv[])
{
	// initalise Indexpointer
	Index* idx = createIndex();

	// add some items
    addRectangle(idx, -50, -50, 50, 50, 0);
    addRectangle(idx, -10, -10, 10, 10, 1);
    addPoint(idx,1,1,2);

    // get nearest two locations to the royal albert hall
	std::vector<SpatialIndex::IData*>* results = getNearest(idx,0,0,1);

}
```

Looking at the source in this repo, it seems that what is causing the difference is the change from `return self._get_ids(it, p_num_results.contents.value)` -> `return self._get_ids(it, min(num_results,p_num_results.contents.value))` in [this commit](https://github.com/Toblerity/rtree/commit/44ad21aecd3f7b49314b9be12f3334d8bae7e827#diff-d81684ea57a4576f3ff7720dd43a08d1R623) by @hobu . 

Since `num_results` is the parameter passed, doesn't this mean that at most `num_results` id's will be returned? That would be contrary to the documentation and behavior of libspatialindex.

Maybe I am missing the point of the change, but I tried reverting it and all tests still pass when running just `pytest`.

**Comment by hobu** [comment]
I was trying to respect the limit that was set by ``p_num_results.contents.value`. It's probable this patch is not correct.

**Comment by adriangb** [comment]
> I was trying to respect the limit that was set by ``p_num_results.contents.value`. It's probable this patch is not correct.

Not sure I fully understand, wouldn't respecting `p_num_results.contents.value` mean the original code is correct? If so, could we open a quick PR to fix this?

**Comment by hobu** [comment]
I think the issue is `num_results` and `p_num_results.contents.value` are not always the same value if the user set a result limit on the index.

**Comment by adriangb** [comment]
Is `p_num_results` an input _and_ outuput for `core.rt.Index_NearestNeighbors_id`?

My assumption from my limited understanding is that it functioned as both an input (`maxResults` input parameter for `getNearest()` in the C++ code I posted above) and as an output (`nResultCount` in the C++ code) so that it would get set to the number of _actual_ results (which may be different from `num_results` if multiple results are at the same distance) and then passed to `_get_ids()` to get the actual number of results (as opposed to the user requested `num_results`).

**Comment by hobu** [comment]
> Is p_num_results an input and output for core.rt.Index_NearestNeighbors_id?

I haven't traced it through. @normanb added that to libspatialindex, but I hadn't used it before, and then I saw it reflected here.

**Comment by adriangb** [comment]
> I haven't traced it through. @normanb added that to libspatialindex, but I hadn't used it before, and then I saw it reflected here.

Okay, hopefully they can chime in. From my limited testing it seems like what I said above is correct, in which case I think that change should be reverted.

Basic testing:
