### ISSUE TITLE
How far off are the binary packages that include libspatialindex?

### ISSUE THREAD

**Issue by Helveg** [Toblerity/rtree#147]
It's currently quite annoying to have Rtree as a dependency because it's not pip installable.

I thought a few months ago that I had seen in other issues that that was a work in progress. What's the status?

**Comment by hobu** [comment]
>  because it's not pip installable.

It's pip installable, there's just no wheels. Please provide a method for creating binary wheels. Otherwise it is just a wait until someone cares enough to provide that.

**Comment by Helveg** [comment]
Ok, do you have any good resources to get me started?

**Comment by hobu** [comment]
I don't have any resources, unfortunately. I don't know very much about wheels and pip, etc. Rtree should be simple to do that for given it only requires libspatialindex, which itself has no dependencies other than glibc or libc++.

**Comment by Helveg** [comment]
So what would the workflow be? An Azure Pipeline that runs on semver tags:

* Clones the latest libspatialindex
* Builds it for a variety of target systems
* Include these binary dependencies in setup.py
* Create the multiple wheels
* Upload the new wheels to PyPI

**Comment by hobu** [comment]
The Azure pipelines already roll up builds of everything for all three platforms. I think the pipelines should be adjusted to script the construction of the wheels using those existing builds. I don't think we should automate the pushing of wheels to PyPI, but we can take the artifacts and manually do it as part of the release process.

**Comment by Helveg** [comment]
Ok a few questions (some of which I'll start looking into myself):

1) When you say the pipelines "already roll up builds", are you referring to https://github.com/Toblerity/rtree/blob/922602026429c121a0cc25ef64a4669b13f58cfd/ci/azp/linux-1804-pip.yml#L8 for example, or something else?

2) What does that apt package install? Is it just a single .so file?

3) What does this Python package require and how does it load the libspatialindex? Run on question: Would it suffice to just include the supposed .so file of question 2 in the same directory as the source files? This would allow us to "vendor" a copy of libspatialindex for each wheel we make (we'll mark the wheel as being platform specific and include the so for linux and the dll for windows).

**Comment by Helveg** [comment]
Ok looking at the source code it seems all this rtree package needs is a .so or .dll file that `ctypes` needs to find. Because I have 0 experience with Azure Pipelines, maybe I can just support you on the Python packaging part of things.

### Mark the package as platform specific

This way you can build the Linux packages from a Linux CI image, Windows from Windows etc. Usually this happens when you add build extensions but since we already have our dependency built we're going to skip this part with a little hack:

Insert this piece of code into `setup.py`. It extends the `bdist_wheel` command so that it always marks the wheel as not being a `pure_lib` --> It contains binary dependencies. (See https://stackoverflow.com/questions/45150304/how-to-force-a-python-wheel-to-be-platform-specific-when-building-it)

```
try:
    from wheel.bdist_wheel import bdist_wheel as _bdist_wheel
    class bdist_wheel(_bdist_wheel):
        def finalize_options(self):
            _bdist_wheel.finalize_options(self)
            self.root_is_pure = False
except ImportError:
    bdist_wheel = None
```

In the `setup(...)` call, specify to use our custom `bdist_wheel` command class instead:

```
setuptools.setup(
     ...
     cmdclass={'bdist_wheel': bdist_wheel}
 )
```

### Copy the .so or .dll file into the Python source dir

I don't know where your .so or .dll file ends up, but I'm sure you can inspect that with for example `dpkg-query -L <package_name>` and just hardcode it if you're a total stranger to bash like me :)

### Tell setuptools to include any .so or .dll files

Usually setuptools only packages `.py` files, but you can specify `package_data`. We'll tell it to include all .so or .dll files:

```
setuptools.setup(
     ...
    include_package_data=True,
    package_data={"rtree": ["*.so", "*.dll"]},
 )
```

### Build the wheel

```
python setup.py bdist_wheel
```

### Use ctypes to load dynamic library

I've never used ctypes, and the docs aren't incredibly clear, but I'm sure you understand it enough to be able to load a dynamic library that will always be located at `os.path.dirname(__file__)`.

## Result

* A platform and python version specific wheel
* Containing a `.so` or `.dll` in the Python source root dir.
* That gets loaded by ctypes.

This should cover us right?

**Comment by Helveg** [comment]
@hobu I'll be trying out an offline version of this on monday where I build libspatialindex from source, copy it to the source dir and run setup.py

If it works can I submit a PR and could you adapt the Azure Pipelines?

**Comment by sr-murthy** [comment]
This would definitely be useful!

**Comment by Helveg** [comment]
See #148 . I succesfully made and installed a self-contained wheel for Linux Python 3.7

These are the steps for the CI if you've checked out the `wheels` branch:
```
git clone git@github.com:libspatialindex/libspatialindex
cd libspatialindex
cmake -DCMAKE_INSTALL_PREFIX=../rtree
make && make install
python setup.py bdist_wheel
```

**Comment by Helveg** [comment]
@hobu so is it currently possible to define `rtree` as a dependency in setuptools and have it succesfully install `rtree` on both Windows and Linux with a simple `pip install my-package`?

**Comment by hobu** [comment]
I made an attempt to automate the generation of wheels with libspatialindex in them in https://github.com/Toblerity/rtree/pull/152 but I failed. Maybe someone else can take what I did and successfully adapt.

**Comment by Helveg** [comment]
Ok, and is it currently possible without wheels? :s

**Comment by Helveg** [comment]
@hobu If I understand correctly you are stuck on an upstream bug right? I've seen a collaborator use CMake to deploy its binary dependency on the target system. Could this be an idea for packaging libspatialindex into rtree for Linux at least? Here's how he did it: https://github.com/arbor-sim/arbor/blob/master/setup.py

**Comment by hobu** [comment]
> stuck on an upstream bug in wheels right?

Yes. The wheel packaging doesn't respect the linkage chain of shared objects for things that are dlopen's ala ctypes. As you can see in the ticket, I spent a lot of time on it and made no progress. I'm not spending any more time on trying. Someone else is going to have to carry this cross.

**Comment by Helveg** [comment]
Ok, could I give the cmake approach a try? It wouldn't result in wheels but it would automatically build libspatialindex on Linux systems as part of the pip installation.

**Comment by hobu** [comment]
> Ok, could I give the cmake approach a try?

Sure. Make a PR and implement the builds using the GitHub Action. That way we can see the results.

**Comment by Helveg** [comment]
Absolutely glorious @hobu it works to generate a `.egg` file. AFAIK when you pip install a `.egg` it runs `python setup.py install` under the hood, and that succesfully created a folder `rtree` in my `site-packages` with a `lib` subdirectory containing the cmake'd .so files: it's compiled on the target, and the target requires cmake (which isn't an unreasonable dependency) and we avoid wheels.

So, could you take a look at https://github.com/Helveg/rtree?

You should be able to test it for yourself with:

```
git clone --recurse-submodules https://github.com/Helveg/rtree
git checkout cmake-install
python setup.py install
```

I'm not sure how to continue with the GitHub Action, I will hack away at it but some clearer instructions/goals could really help me along.

**Comment by hobu** [comment]
In regards to your branch, is it really the Python Way to use git submodules for dependent libraries? I'm so far out of the loop on Python packaging anymore, but I don't think this is what people prescribe. 

I can fully appreciate that this gets things working for you, but I don't want to codify what might be a bad packaging behavior. Rtree is weird because of the ctypes usage. Maybe the thing to do is to attack that with something like Cython. It would have other benefits as well.

**Comment by Helveg** [comment]
@hobu The gitmodule is definitly not a required part, it was indeed soemthing I hesitantly introduced "to get it working" but it can be replaced by a `git clone` of libspatialindex during the CI step! I have no experience with Cython and the problem is that this is becoming time sensitive for me so I'd like to move forward with providing rtree out of the box without extra install steps of libspatialindex. I don't mind that my work gets overwritten with a Cython approach at a later stage.

For now, could you tell me what I'm supposed to do as far as GitHub actions goes?

**Comment by hobu** [comment]
I see, you're not suggesting adding libspatialindex as a submodule for the project, only during the build process.

**Comment by Helveg** [comment]
Well, I think that cloning it during the build process should suffice aswell, no submodules required. I just hadn't started on the builds yet, I am waiting for instructions on what the builds should do exactly :)

I'll just go ahead and make a script `build_linux_eggs.sh` that produces the egg build artifacts in the `dist` folder and I'll make a PR. It would be great if you could make some time in the near future to talk me through what still needs to happen for the Github Actions you mentioned and to get the PR approved and these eggs available for distribution. 

Please contact me on `robingilbert.deschepper@unipv.it` if you have the time.

**Comment by Helveg** [comment]
While I'm waiting for libspatialindex/libspatialindex#190 I've uploaded Linux and Windows wheels for 0.9.4 under the name [`rtree-linux`](https://pypi.org/project/Rtree-linux/) on PyPI for those that like wheels :) I'm hoping the MacOS issue can be resolved so that #156 can pass

**Comment by hobu** [comment]
@Helveg unfortunately I don't have any cycles for this or the libspatialindex issue for a few weeks. When I do, I'll issue a new libspatialindex point release with the rpath fix.

**Comment by Helveg** [comment]
That's great news! Thanks alot for all your work on this, I'm glad we found an approach that seems to meet all requirements!

**Comment by KPLauritzen** [comment]
@Helveg 


> While I'm waiting for [libspatialindex/libspatialindex#190](https://github.com/libspatialindex/libspatialindex/issues/190) I've uploaded Linux and Windows wheels for 0.9.4 under the name [`rtree-linux`](https://pypi.org/project/Rtree-linux/) on PyPI for those that like wheels :) I'm hoping the MacOS issue can be resolved so that #156 can pass

Thanks so much for this. This was super helpful for me. I'm building a small set of tools using `geopandas`, and for many of the features I need, `rtree` is required. This helps enormously with distributing my work. 

Hope this gets integrated into rtree proper at some point.

**Comment by hobu** [comment]
Is Rtree a requirement of geopandas?

**Comment by mwtoews** [comment]
> Is Rtree a requirement of geopandas?

With I think version 0.7 it was an optional dependancy, and it found with the .sindex property for a GeoSeries or GeoDataFrame. Without Rtree, .sindex was None. But I noticed in version 0.8 that .sindex is now PyGEOSSTRtree. No mention of this in the geopandas release notes, however. This means that .sindex.nearest is currently available from Rtree, as the PyGEOS folks are still bringing in the nearest method.

**Comment by hobu** [comment]
Please try 0.9.6 which include libspatialindex builds in wheels
