### ISSUE TITLE
rtree 0.9.4 not working with libspatialindex 1.9.3

### ISSUE THREAD

**Issue by daneisenberg-nps** [Toblerity/rtree#153]
## Problem
I recently created a new conda environment to get the newest version of geopandas (0.7.0). After installing all dependencies using conda-forge, I started to receive the following error [OSError: could not find or load spatialindex_c-64.dll ] (copied below). (if it helps I'm running Windows 10 x64).

### Error using rtree 0.9.4 with libspatialindex 1.9.3
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-2d057460dc59> in <module>
      1 import fiona
----> 2 import geopandas as gpd
      3 import os
      4 import re

~\Anaconda3\envs\geo_env1\lib\site-packages\geopandas\__init__.py in <module>
----> 1 from geopandas.geoseries import GeoSeries  # noqa
      2 from geopandas.geodataframe import GeoDataFrame  # noqa
      3 from geopandas.array import _points_from_xy as points_from_xy  # noqa
      4 
      5 from geopandas.io.file import read_file  # noqa

~\Anaconda3\envs\geo_env1\lib\site-packages\geopandas\geoseries.py in <module>
     11 from shapely.ops import transform
     12 
---> 13 from geopandas.base import GeoPandasBase, _delegate_property
     14 from geopandas.plotting import plot_series
     15 

~\Anaconda3\envs\geo_env1\lib\site-packages\geopandas\base.py in <module>
     15 
     16 try:
---> 17     from rtree.core import RTreeError
     18 
     19     HAS_SINDEX = True

~\Anaconda3\envs\geo_env1\lib\site-packages\rtree\__init__.py in <module>
----> 1 from .index import Rtree
      2 
      3 from .core import rt
      4 
      5 __version__ = '0.9.4'

~\Anaconda3\envs\geo_env1\lib\site-packages\rtree\index.py in <module>
      4 import pprint
      5 
----> 6 from . import core
      7 
      8 import pickle

~\Anaconda3\envs\geo_env1\lib\site-packages\rtree\core.py in <module>
    124         rt = _load_library(lib_name, ctypes.cdll.LoadLibrary)
    125     if not rt:
--> 126         raise OSError("could not find or load %s" % lib_name)
    127 
    128 elif os.name == 'posix':

OSError: could not find or load spatialindex_c-64.dll

---------------------------------------------------------------------------

## Possible issue / fix
After downgrading rtree to version 0.9.3, the error goes away. Previous stackoverflow and github issues describing a similar OSError with rtree 0.9.3 said this was caused when libspatialindex was not installed. However, I have libspatialindex installed from conda-forge in both cases (conda list for both environments copied below).

I'm not sure exactly whats wrong, but it looks like there was a change between rtree version 0.9.3 and 0.9.4 in core.py between lines 118-129 where the _Load_Library function is called without setting a lib_path. This is only difference I can see between versions.

### Code snippet rtree 0.9.3, core.py lines 118-129:
```
lib_name = '%s-%s.dll' % (base_name, arch)
if 'SPATIALINDEX_C_LIBRARY' in os.environ:
    lib_path, lib_name = os.path.split(os.environ['SPATIALINDEX_C_LIBRARY'])
    rt = _load_library(lib_name, ctypes.cdll.LoadLibrary, (lib_path,))
elif 'conda' in sys.version:
    lib_path = os.path.join(sys.prefix, "Library", "bin")
    rt = _load_library(lib_name, ctypes.cdll.LoadLibrary, (lib_path,))
else:
    lib_path = os.path.join(sys.prefix, "Library", "bin")
    rt = _load_library(lib_name, ctypes.cdll.LoadLibrary, (lib_path,))
if not rt:
    raise OSError("could not find or load %s" % lib_name)
```

### Code snippet rtree 0.9.4, core.py lines 116-126:
```
lib_name = '%s-%s.dll' % (base_name, arch)
if 'SPATIALINDEX_C_LIBRARY' in os.environ:
    lib_path, lib_name = os.path.split(os.environ['SPATIALINDEX_C_LIBRARY'])
    rt = _load_library(lib_name, ctypes.cdll.LoadLibrary, (lib_path,))
elif 'conda' in sys.version:
    lib_path = os.path.join(sys.prefix, "Library", "bin")
    rt = _load_library(lib_name, ctypes.cdll.LoadLibrary, (lib_path,))
else:
    rt = _load_library(lib_name, ctypes.cdll.LoadLibrary)
if not rt:
    raise OSError("could not find or load %s" % lib_name)
```

### conda list after geopandas install using conda-forge (rtree 0.9.4)
attrs                     19.3.0                     py_0
backcall                  0.1.0                    py38_0
bleach                    3.1.4                      py_0
boost-cpp                 1.72.0               h0caebb8_0    conda-forge
branca                    0.4.0                      py_0    conda-forge
brotlipy                  0.7.0           py38h1e8a9f7_1000    conda-forge
bzip2                     1.0.8                hfa6e2cd_2    conda-forge
ca-certificates           2020.1.1                      0    anaconda
cartopy                   0.17.0          py38hde43876_1009    conda-forge
certifi                   2020.4.5.1               py38_0    anaconda
cffi                      1.14.0           py38ha419a9e_0    conda-forge
cfitsio                   3.470                hfa6e2cd_2    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
click                     7.1.1              pyh8c360ce_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
colorama                  0.4.3                      py_0
cryptography              2.8              py38hb32ad35_1    conda-forge
curl                      7.68.0               h4496350_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py38_0
expat                     2.2.9                he025d50_2    conda-forge
fiona                     1.8.13           py38hb7fdc2d_0    conda-forge
folium                    0.10.1                     py_0    conda-forge
freetype                  2.10.1               ha9979f8_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      3.0.2            py38hdf43c64_0
geopandas                 0.7.0                      py_1    conda-forge
geos                      3.8.0                he025d50_1    conda-forge
geotiff                   1.5.1                h5770a2b_0
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.9                        py_1    conda-forge
importlib_metadata        1.5.0                    py38_0
intel-openmp              2020.0                      166
ipykernel                 5.1.4            py38h39e3cac_0
ipython                   7.13.0           py38h5ca1d4c_0
ipython_genutils          0.2.0                    py38_0
ipywidgets                7.5.1                      py_0
jedi                      0.16.0                   py38_1
jinja2                    2.11.1                     py_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                    py38_0
jupyter                   1.0.0                    py38_7
jupyter_client            6.1.2                      py_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.3                    py38_0
kealib                    1.4.7                h07cbb95_6
kiwisolver                1.2.0            py38heaebd3c_0    conda-forge
krb5                      1.16.4               hdd46e55_0    conda-forge
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
libcurl                   7.68.0               h4496350_0    conda-forge
libgdal                   3.0.2                h1155b67_0
libiconv                  1.15              hfa6e2cd_1006    conda-forge
libkml                    1.3.0             h7e985d0_1011    conda-forge
liblapack                 3.8.0                    15_mkl    conda-forge
libnetcdf                 4.6.1                h411e497_2
libpng                    1.6.37               h2a8f88b_0
libpq                     11.5                 hb0bdaea_2    conda-forge
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             4.3.0a            he9c6e69_1033    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.1.0                h56a325e_0
libxml2                   2.9.10               h9ce36c8_0    conda-forge
lz4                       3.0.2            py38h683b9b5_1    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py38he774522_0
matplotlib-base           3.2.1            py38h1626042_0    conda-forge
mistune                   0.8.4           py38he774522_1000
mkl                       2020.0                      166
msys2-conda-epoch         20160418                      1
munch                     2.5.0                      py_0    conda-forge
nbconvert                 5.6.1                    py38_0
nbformat                  5.0.4                      py_0
notebook                  6.0.3                    py38_0
numpy                     1.18.1           py38ha749109_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1                he774522_0    anaconda
owslib                    0.19.2                     py_1    conda-forge
pandas                    1.0.3            py38he6e81aa_1    conda-forge
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py38_1
parso                     0.6.2                      py_0
pcre                      8.44                 h6538335_0    conda-forge
pickleshare               0.7.5                 py38_1000
pillow                    7.0.0            py38hcc1f983_0
pip                       20.0.2                   py38_1
postgresql                11.5                 h06f7779_2    conda-forge
proj                      6.2.1                ha7a8c7b_0    conda-forge
prometheus_client         0.7.1                      py_0
prompt-toolkit            3.0.4                      py_0
prompt_toolkit            3.0.4                         0
pycparser                 2.20                       py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.6.1                      py_0
pykdtree                  1.3.1           py38h4b8e87e_1003    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.4.2.post1      py38h9716dcf_0    conda-forge
pyqt                      5.9.2            py38ha925a31_4
pyrsistent                0.16.0           py38he774522_0
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.2               h5fd99cc_11
python-dateutil           2.8.1                      py_0
python_abi                3.8                      1_cp38    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywin32                   227              py38he774522_1
pywinpty                  0.5.7                    py38_0
pyyaml                    5.3.1            py38h9de7a3e_0    conda-forge
pyzmq                     18.1.1           py38ha925a31_0
qt                        5.9.7            vc14h73c81de_0
qtconsole                 4.7.2                      py_0
qtpy                      1.9.0                      py_0
requests                  2.23.0             pyh8c360ce_2    conda-forge
rtree                     0.9.4            py38h7ad75cc_1    conda-forge
scipy                     1.3.2            py38h582fac2_0    conda-forge
send2trash                1.5.0                    py38_0
setuptools                46.1.3                   py38_0
shapely                   1.7.0            py38h68b7539_1    conda-forge
sip                       4.19.13          py38ha925a31_0
six                       1.14.0                   py38_0
sqlite                    3.31.1               he774522_0
tbb                       2018.0.5             he980bc4_0    conda-forge
terminado                 0.8.3                    py38_0
testpath                  0.4.4                      py_0
tiledb                    1.6.3                h7b000aa_0
tk                        8.6.10               hfa6e2cd_0    conda-forge
tornado                   6.0.4            py38he774522_1
traitlets                 4.3.3                    py38_0
ttkthemes                 3.0.0                    pypi_0    pypi
urllib3                   1.25.9                     py_0    conda-forge
vc                        14.1                 h0510ff6_4
vincent                   0.4.4                      py_1    conda-forge
vs2015_runtime            14.16.27012          hf0eaf9b_1
wcwidth                   0.1.9                      py_0
webencodings              0.5.1                    py38_1
wheel                     0.34.2                   py38_0
widgetsnbextension        3.5.1                    py38_0
win_inet_pton             1.1.0                    py38_0    conda-forge
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
xerces-c                  3.2.3                ha925a31_0    conda-forge
xz                        5.2.5                h2fa13f4_0    conda-forge
yaml                      0.2.4                he774522_0    conda-forge
zeromq                    4.3.1                h33f27b4_3
zipp                      2.2.0                      py_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.3.7             haafe652_1001    conda-forge

### conda list after downgrading rtree to version 0.9.3
Name                    Version                   Build  Channel
attrs                     19.3.0                     py_0
backcall                  0.1.0                    py38_0
bleach                    3.1.4                      py_0
boost-cpp                 1.72.0               h0caebb8_0    conda-forge
branca                    0.4.0                      py_0    conda-forge
brotlipy                  0.7.0           py38h1e8a9f7_1000    conda-forge
bzip2                     1.0.8                hfa6e2cd_2    conda-forge
ca-certificates           2020.1.1                      0
cartopy                   0.17.0          py38hde43876_1009    conda-forge
certifi                   2020.4.5.1               py38_0
cffi                      1.14.0           py38ha419a9e_0    conda-forge
cfitsio                   3.470                hfa6e2cd_2    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
click                     7.1.1              pyh8c360ce_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
colorama                  0.4.3                      py_0
cryptography              2.8              py38hb32ad35_1    conda-forge
curl                      7.68.0               h4496350_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
entrypoints               0.3                      py38_0
expat                     2.2.9                he025d50_2    conda-forge
fiona                     1.8.13           py38hb7fdc2d_0    conda-forge
folium                    0.10.1                     py_0    conda-forge
freetype                  2.10.1               ha9979f8_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      3.0.2            py38hdf43c64_0
geopandas                 0.7.0                      py_1    conda-forge
geos                      3.8.0                he025d50_1    conda-forge
geotiff                   1.5.1                h5770a2b_0
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.9                        py_1    conda-forge
importlib_metadata        1.5.0                    py38_0
intel-openmp              2020.0                      166
ipykernel                 5.1.4            py38h39e3cac_0
ipython                   7.13.0           py38h5ca1d4c_0
ipython_genutils          0.2.0                    py38_0
ipywidgets                7.5.1                      py_0
jedi                      0.16.0                   py38_1
jinja2                    2.11.1                     py_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                    py38_0
jupyter                   1.0.0                    py38_7
jupyter_client            6.1.2                      py_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.3                    py38_0
kealib                    1.4.7                h07cbb95_6
kiwisolver                1.2.0            py38heaebd3c_0    conda-forge
krb5                      1.16.4               hdd46e55_0    conda-forge
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
libcurl                   7.68.0               h4496350_0    conda-forge
libgdal                   3.0.2                h1155b67_0
libiconv                  1.15              hfa6e2cd_1006    conda-forge
libkml                    1.3.0             h7e985d0_1011    conda-forge
liblapack                 3.8.0                    15_mkl    conda-forge
libnetcdf                 4.6.1                h411e497_2
libpng                    1.6.37               h2a8f88b_0
libpq                     11.5                 hb0bdaea_2    conda-forge
libsodium                 1.0.16               h9d3ae62_0
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             4.3.0a            he9c6e69_1033    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.1.0                h56a325e_0
libxml2                   2.9.10               h9ce36c8_0    conda-forge
lz4                       3.0.2            py38h683b9b5_1    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py38he774522_0
matplotlib-base           3.2.1            py38h1626042_0    conda-forge
mistune                   0.8.4           py38he774522_1000
mkl                       2020.0                      166
msys2-conda-epoch         20160418                      1
munch                     2.5.0                      py_0    conda-forge
nbconvert                 5.6.1                    py38_0
nbformat                  5.0.4                      py_0
notebook                  6.0.3                    py38_0
numpy                     1.18.1           py38ha749109_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1g               he774522_0
owslib                    0.19.2                     py_1    conda-forge
pandas                    1.0.3            py38he6e81aa_1    conda-forge
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py38_1
parso                     0.6.2                      py_0
pcre                      8.44                 h6538335_0    conda-forge
pickleshare               0.7.5                 py38_1000
pillow                    7.0.0            py38hcc1f983_0
pip                       20.0.2                   py38_1
postgresql                11.5                 h06f7779_2    conda-forge
proj                      6.2.1                ha7a8c7b_0    conda-forge
prometheus_client         0.7.1                      py_0
prompt-toolkit            3.0.4                      py_0
prompt_toolkit            3.0.4                         0
pycparser                 2.20                       py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.6.1                      py_0
pykdtree                  1.3.1           py38h4b8e87e_1003    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.4.2.post1      py38h9716dcf_0    conda-forge
pyqt                      5.9.2            py38ha925a31_4
pyrsistent                0.16.0           py38he774522_0
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.2               h5fd99cc_11
python-dateutil           2.8.1                      py_0
python_abi                3.8                      1_cp38    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywin32                   227              py38he774522_1
pywinpty                  0.5.7                    py38_0
pyyaml                    5.3.1            py38h9de7a3e_0    conda-forge
pyzmq                     18.1.1           py38ha925a31_0
qt                        5.9.7            vc14h73c81de_0
qtconsole                 4.7.2                      py_0
qtpy                      1.9.0                      py_0
requests                  2.23.0             pyh8c360ce_2    conda-forge
rtree                     0.9.3            py38h21ff451_0
scipy                     1.3.2            py38h582fac2_0    conda-forge
send2trash                1.5.0                    py38_0
setuptools                46.1.3                   py38_0
shapely                   1.7.0            py38h68b7539_1    conda-forge
sip                       4.19.13          py38ha925a31_0
six                       1.14.0                   py38_0
sqlite                    3.31.1               he774522_0
tbb                       2018.0.5             he980bc4_0    conda-forge
terminado                 0.8.3                    py38_0
testpath                  0.4.4                      py_0
tiledb                    1.6.3                h7b000aa_0
tk                        8.6.10               hfa6e2cd_0    conda-forge
tornado                   6.0.4            py38he774522_1
traitlets                 4.3.3                    py38_0
ttkthemes                 3.0.0                    pypi_0    pypi
urllib3                   1.25.9                     py_0    conda-forge
vc                        14.1                 h0510ff6_4
vincent                   0.4.4                      py_1    conda-forge
vs2015_runtime            14.16.27012          hf0eaf9b_1
wcwidth                   0.1.9                      py_0
webencodings              0.5.1                    py38_1
wheel                     0.34.2                   py38_0
widgetsnbextension        3.5.1                    py38_0
win_inet_pton             1.1.0                    py38_0    conda-forge
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
xerces-c                  3.2.3                ha925a31_0    conda-forge
xz                        5.2.5                h2fa13f4_0    conda-forge
yaml                      0.2.4                he774522_0    conda-forge
zeromq                    4.3.1                h33f27b4_3
zipp                      2.2.0                      py_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.3.7             haafe652_1001    conda-forge

**Comment by hobu** [comment]
I think the issue here is how Python 3.8 does DLL resolution. There's some conda magic that gets run now (search for ``CONDA_DLL_SEARCH_MODIFICATION_ENABLE``) on 3.8 installations to change the path resolution. Rtree 0.9.4 is doing a ctypes load of a relative path too, which brings the DLL loading resolution into play.

Can you try downgrading to `python=3.7` and see if 0.9.4 actually works for you? If so, can you then try Rtree master? I've made a few changes to the path resolution since we last released. Please report back. I was about ready to release 0.9.5 anyway, so lets get this issue knocked down before we do.

**Comment by daneisenberg-nps** [comment]
Thanks for the reply @hobu 

I am in meetings for a little while, but will try this later today.

**Comment by daneisenberg-nps** [comment]
@hobu your suspicion about python 3.8 seems correct. Here's what I tried.
An environment with geopandas 0.7.0 (conda-forge) and:
* python 3.7.7 + Rtree 0.9.4 (conda-forge): no error
* python 3.7.7 + Rtree 0.9.4 (master): no error
* python 3.8.2 + Rtree 0.9.4 (conda-forge): error (original env build)
* python 3.8.2 + Rtree 0.9.4 (master): error 
* python 3.8.2 + Rtree 0.9.3: no error

**Comment by hobu** [comment]
Thanks for the info. I'll try to work this into a patch.

**Comment by hobu** [comment]
Please try 0.9.6 and see if this is now working.
