### ISSUE TITLE
Can't serialize rtree index when using stream loading

### ISSUE THREAD

**Issue by carlosg-m** [Toblerity/rtree#159]
This is my setup. I use a generator to get bounding boxes from a Dask DataFrame and feed them to the rtree.

```
def rtree_gen(gen):
  for item in gen:
    index, bounds = item[0], item[1:]
    yield index, bounds, None
  
troco_sindex_gen = troco[['minx','miny','maxx','maxy']].itertuples(name=None)
troco_sindex_gen = rtree_gen(troco_sindex_gen)
```

Doing this is very fast and works while the tree object is on memory. **However it's not possible to serialize, resulting index files (rtree.idx, rtree.dat) will be empty in disk.**
```
troco_sindex = rtree.index.Index(troco_sindex_gen, 'rtree')

troco_sindex.close()

# This does not work
load_tree = rtree.index.Index('rtree')
```

However when using the "insert" method, the serialization works and it's possible to load the tree from disk, while being much slower to create.

```
troco_sindex = rtree.index.Index('rtree')

for index, bb, _ in troco_sindex_gen:
  troco_sindex.insert(index, bb)

troco_sindex.close()

# This works
load_tree = rtree.index.Index('rtree')
```

**Comment by hobu** [comment]
Please produce a test case that takes Dask and everything out of it. You can see our streaming test case at https://github.com/Toblerity/rtree/blob/master/tests/test_index.py#L421 which is pretty much this scenario.
