### ISSUE TITLE
Are both Geographic coordinate systems and Projected coordinate systems supported?

### ISSUE THREAD

**Issue by carlosg-m** [Toblerity/rtree#160]
Does this library expect input coordinates to be in a cartesian plane or does it also work with WGS84?

The 3d index expects ECEF coordinates like pyinterp.RTree?

https://pangeo-pyinterp.readthedocs.io/en/latest/generated/pyinterp.RTree.html

**Comment by hobu** [comment]
> Does this library expect input coordinates to be in a cartesian plane

Yes. Rtree does not support geodesic operations. Look into GeographicLib or PostGIS if you need support for that.

**Comment by carlosg-m** [comment]
Thank you!
