### ISSUE TITLE
How to bulk load?

### ISSUE THREAD

**Issue by gcoimbra** [Toblerity/rtree#165]
I see that we have support for STR bulk loading, but how to use it? I didn't find any docs about it.
In my application is really needed to minimize overlapping  for building the tree, so I need to be sure that I'm using STR. This is why stackoverflow answers don't seem to be sufficient...

Thanks about the package, is very useful!

**Comment by hobu** [comment]
Use the streaming interface. See https://github.com/Toblerity/rtree/blob/master/tests/test_index.py#L421 for an example.

**Comment by gcoimbra** [comment]
@hobu 
I've used that code to bulk load compared to idx.insert every bounding box and then performed some tests.
I tested 994825 points and inserted 5570 polygons of cities, and the time for both methods remained the same, also tested with 300k smaller polygons.
I expected that with STR loading the time will be much lower.
Any idea of why this?
