### ISSUE TITLE
I and others are getting this error I finally got it to install after numerous attempts but I don't know why. 

### ISSUE THREAD

**Issue by OldSubSailor** [Toblerity/rtree#171]
Collecting rtree
Using cached Rtree-0.9.4.tar.gz (62 kB)
ERROR: Command errored out with exit status 1:
command: /Library/Frameworks/Python.framework/Versions/3.9/bin/
python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/
private/var/folders/c8/s5_gtsmd6v9bksgjpphm79c80000gn/T/pipinstall-
33gs7qtf/rtree/setup.py'"'"'; __file__='"'"'/private/var/
folders/c8/s5_gtsmd6v9bksgjpphm79c80000gn/T/pip-install-33gs7qtf/
rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)
(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
egg_info --egg-base /private/var/folders/c8/
s5_gtsmd6v9bksgjpphm79c80000gn/T/pip-pip-egg-info-rjup97lk
cwd: /private/var/folders/c8/s5_gtsmd6v9bksgjpphm79c80000gn/
T/pip-install-33gs7qtf/rtree/
Complete output (15 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/private/var/folders/c8/s5_gtsmd6v9bksgjpphm79c80000gn/T/
pip-install-33gs7qtf/rtree/setup.py", line 3, in <module>
import rtree
File "/private/var/folders/c8/s5_gtsmd6v9bksgjpphm79c80000gn/T/
pip-install-33gs7qtf/rtree/rtree/__init__.py", line 1, in <module>
from .index import Rtree
File "/private/var/folders/c8/s5_gtsmd6v9bksgjpphm79c80000gn/T/
pip-install-33gs7qtf/rtree/rtree/index.py", line 6, in <module>
from . import core
File "/private/var/folders/c8/s5_gtsmd6v9bksgjpphm79c80000gn/T/
pip-install-33gs7qtf/rtree/rtree/core.py", line 143, in <module>
rt.Error_GetLastErrorNum.restype = ctypes.c_int
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/
python3.9/ctypes/__init__.py", line 387, in __getattr__
func = self.__getitem__(name)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/
python3.9/ctypes/__init__.py", line 392, in __getitem__
func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol
not found
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py
egg_info Check the logs for full command output.

**Comment by hobu** [comment]
Please try 0.9.6

**Comment by OldSubSailor** [comment]
Its been a while since submitted, however,
% pip3 show Rtree  
Name: Rtree
Version: 0.9.4
Summary: R-Tree spatial index for Python GIS
Home-page: https://github.com/Toblerity/rtree
Author: Sean Gillies
Author-email: sean.gillies@gmail.com
License: MIT
Location: /Users/trav/Library/Python/3.9/lib/python/site-packages
Requires: setuptools
Required-by:
