### ISSUE TITLE
Use post<N> suffix for release tags with no source changes

### ISSUE THREAD

**Issue by sebastic** [Toblerity/rtree#177]
The last few releases have not contained any source changes and seemed to have served only to update the binary wheels.

Please use the `post<N>` suffix for the tags of such releases like Fiona to allow downstreams to skip packaging those.

**Comment by hobu** [comment]
> Please use the post<N> suffix for the tags of such releases like Fiona to allow downstreams to skip packaging those.

Will do next time. There shouldn't be any more release churn anymore either.
