### ISSUE TITLE
rtree broken with Python 3.8.8

### ISSUE THREAD

**Issue by sweettyler** [Toblerity/rtree#182]
When I tried to import rtree, I got the following error:

Python 3.8.8 (default, Feb 24 2021, 21:46:12) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.21.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import rtree
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-eac81b9ced24> in <module>
----> 1 import rtree

~/anaconda3/lib/python3.8/site-packages/rtree/__init__.py in <module>
----> 1 from .index import Rtree
      2 
      3 from .core import rt
      4 
      5 __version__ = '0.9.4'

~/anaconda3/lib/python3.8/site-packages/rtree/index.py in <module>
      4 import pprint
      5 
----> 6 from . import core
      7 
      8 import pickle

~/anaconda3/lib/python3.8/site-packages/rtree/core.py in <module>
    141     raise RTreeError('Unsupported OS "%s"' % os.name)
    142 
--> 143 rt.Error_GetLastErrorNum.restype = ctypes.c_int
    144 
    145 rt.Error_GetLastErrorMsg.argtypes = []

~/anaconda3/lib/python3.8/ctypes/__init__.py in __getattr__(self, name)
    392         if name.startswith('__') and name.endswith('__'):
    393             raise AttributeError(name)
--> 394         func = self.__getitem__(name)
    395         setattr(self, name, func)
    396         return func

~/anaconda3/lib/python3.8/ctypes/__init__.py in __getitem__(self, name_or_ordinal)
    397 
    398     def __getitem__(self, name_or_ordinal):
--> 399         func = self._FuncPtr((name_or_ordinal, self))
    400         if not isinstance(name_or_ordinal, int):
    401             func.__name__ = name_or_ordinal

AttributeError: ~/anaconda3/bin/python: undefined symbol: Error_GetLastErrorNum

In [2]: quit

**Comment by sweettyler** [comment]
I found this because I found spyder stopped working after some Anaconda updates. Please refer https://github.com/ContinuumIO/anaconda-issues/issues/12301 for some detail

**Comment by itssimon** [comment]
Same here. Got it to work again by downgrading Python to 3.8.6. I'm using conda-forge to install Python and rtree.

**Comment by hobu** [comment]
I can't fix this bug without details that discriminate why 3.8.8 is behaving any different than 3.8.6.

**Comment by sweettyler** [comment]
@hobu see the first post where I just tried to import rtree, the error is :
~/anaconda3/lib/python3.8/site-packages/rtree/core.py in
raise RTreeError('Unsupported OS "%s"' % os.name)

**Comment by sweettyler** [comment]
@hobu you can close this ticket as Anaconda has released a new Python 3.8.8 (v5) and this issue has been fixed.

**Comment by hobu** [comment]
> you can close this ticket as Anaconda has released a new Python 3.8.8 (v5) and this issue has been fixed.

Do you have a link to the ticket or reason why 3.8.8 did something different to fix this issue that was shown in Rtree? Just curious why Rtree was impacted.

**Comment by sweettyler** [comment]
I did report the bug to them but as of today I haven't gotten any response.
