### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [Toblerity/rtree#183]
Problem
---------
On aarch64, pip install rtree builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install rtree should download the wheels from pypi

@hobu, please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by hobu** [comment]
The next release will include aarch64 wheels thanks to this effort.
