### ISSUE TITLE
broken conda-forge build?

### ISSUE THREAD

**Issue by raphaelquast** [Toblerity/rtree#195]
If i install `rtree` with `conda install -c conda-forge rtree` on Windows10 I get the following error:

    OSError: could not find or load spatialindex_c-64.dll

however installing it with `conda install rtree` (without conda-forge) all works just as expected!

This is most probably also what's happening in #191 and #179.
... also on stackexchange people report similar experiences: https://gis.stackexchange.com/a/390568

Any chance of getting an updated release on `conda-forge` ?

**Comment by mwtoews** [comment]
Duplicate of https://github.com/conda-forge/rtree-feedstock/issues/31
