### ISSUE TITLE
"Empty data stream given" error

### ISSUE THREAD

**Issue by sgillies** [Toblerity/rtree#20]
Trying to set GeoPandas up with Rtree support today I have run into the following:

`RTreeError: Error in "Index_CreateWithStream": IllegalArgumentException: RTree::BulkLoader::bulkLoadUsingSTR: Empty data stream given.`

If the generator you send to the bulk loader turns out to be empty, say you filter all its element out for good reasons, leaving only an expression equivalent to

```
idx = Index(iter(()))
```

the bulk loader quits and raises an exception. More graceful failure would be better.

**Comment by nchidsey** [comment]
This is still a bug, is it not?  It is legal to make an empty index without a stream using `Index()`, so an empty generator should be acceptable too, just as described in the original comment above.
