### ISSUE TITLE
Saving and loading an Rtree into/from disk

### ISSUE THREAD

**Issue by Elhamahm** [Toblerity/rtree#200]
Hi dear authors,
Could you please guide how the rtree can be saved and loaded into/from disk in python? Thanks
Ella

**Comment by hobu** [comment]
This is in the docs https://rtree.readthedocs.io/en/latest/

**Comment by Elhamahm** [comment]
Hi Toblerity,

Actually when I load the pre-saved indexing tree and check its bounding I
get the wrong answer. For example, the loaded indexing tree (file_idx2)' s
boundaries are different from the original tree (idx2) 's boundaries.
Please advise!

Thanks
Elham
