### ISSUE TITLE
Loaded r*-tree returns wrong boundreis. 

### ISSUE THREAD

**Issue by Elhamahm** [Toblerity/rtree#201]
Dear Authors, 

I have a question regarding saving and loading R*-tree
Actually when I load the pre-saved indexing tree and check its bounding box, I get the wrong answer. For example, the loaded indexing tree (file_idx2)' s boundaries are different from the original tree (idx2) 's boundaries. Please advise! Thanks

![image](https://user-images.githubusercontent.com/7827229/148988501-250339b5-0a47-4f9d-9b71-389d9b4713bc.png)

**Comment by hobu** [comment]
Look at the tests for examples https://github.com/Toblerity/rtree/blob/master/tests/test_index.py
