### ISSUE TITLE
Minimum supported version of libspatialindex

### ISSUE THREAD

**Issue by adamjstewart** [Toblerity/rtree#211]
According to:

* `DEPENDENCIES.txt`
* `docs/source/install.txt`
* `rtree/index.py`

the minimum supported version of lispatialindex is 1.7.0. However, according to:

* `docs/source/README.txt`

the minimum supported version of libspatialindex is 1.8.5.

Which is it? We should make the documentation uniform.

**Comment by hobu** [comment]
It is probably 1.8.5 at this point.
