### ISSUE TITLE
Mismatch between package and New M1 apple silicon

### ISSUE THREAD

**Issue by aranreisman** [Toblerity/rtree#230]
Hi, 

There seems to be an issue installing the current version (0.9.7) on apple silicon base Macbook Pros on OS Monterey.
Seems like this is dues to mismatch as to were libspatialindex is installed in the OS.

Are there any releases scheduled for the near future?
Are you aware of this issue?

Thanks,
Aran

**Comment by hobu** [comment]
#224 #206 #193
