### ISSUE TITLE
Python 3.10 wheels

### ISSUE THREAD

**Issue by adamjstewart** [Toblerity/rtree#232]
Could we get wheels for Python 3.10? I don't think this would require a new release, you should be able to build wheels for the current release and upload them.

**Comment by hobu** [comment]
They are done and ready for once we make the new release.

**Comment by adamjstewart** [comment]
Any idea when the new release will be? I hate to put pressure on you for a release just so we can get Python 3.10 wheels, but I would love to start testing TorchGeo with Python 3.10
