### ISSUE TITLE
Using rtree in Cygwin

### ISSUE THREAD

**Issue by mijaba** [Toblerity/rtree#244]
I installed rtree using pip within Cygwin. Importing rtree would then fail, raising `OSError: Could not load libspatialindex_c library`.  I compiled libspatialindex manually and tried again, but still saw the same OSError.

After examining finder.py, I managed to get it working. Where it went wrong is that the `os.name` is `posix` and `platform.system()` is  `CYGWIN_NT-10.0-19042`. The `lib_name` variable is then assumed to be right for Linux (`libspatialindex_c.so`), but the name is different (`cygspatialindex_c-6.dll`). 

I added an `elif` branch to test whether the `platform.system()` starts with `CYGWIN_NT`, setting `lib_name` to `cygspatialindex_c-6.dll`. With that, rtree now works for me. 

I haven't made a patch, as I doubt this is anywhere near a general solution, but perh

**Comment by mwtoews** [comment]
I had a go at this, and didn't see any issues.

1. Compile and install libspatialindex (master branch) using cmake, with a modification to comment-out `set(CMAKE_CXX_EXTENSIONS OFF)`, use default install prefix `/usr/local`
2. Build binary wheels for Rtree (master branch) using: `python -m build`, which should hopefully discover libspatialindex
3. Install using (e.g.) `python -m pip install dist/Rtree-1.0.0-cp39-cp39-cygwin_3_3_4_x86_64.whl`
