### ISSUE TITLE
Please release a new version with the type hints support

### ISSUE THREAD

**Issue by chriskilding** [Toblerity/rtree#246]
I upgraded my project to rtree 1.0.0 as the release notes said this version added type hint support.

But the type hints were not quite usable in 1.0.0; the `py.typed` file was added afterwards in [81cc81a](https://github.com/Toblerity/rtree/commit/81cc81a1f11081992bf2715bd82d08eca3e48e4e).

Please could a new version be released to make these changes available?

**Comment by hobu** [comment]
Should be released in 1.0.1
