### ISSUE TITLE
Release publishing automation

### ISSUE THREAD

**Issue by hobu** [Toblerity/rtree#302]
My homespun release automation [has broken](https://github.com/Toblerity/rtree/pull/300#issuecomment-1900339523) due to a bad token or something. We should take advantage of the new [Trusted Publishing](https://github.com/marketplace/actions/pypi-publish#trusted-publishing) stuff that PyPI now provides, however.

https://github.com/Toblerity/rtree/pull/300#issuecomment-1900575391

**Comment by mwtoews** [comment]
xref to #299 for the most recent rewrite

**Comment by mwtoews** [comment]
In theory this is done. The [most recent publish event failed](https://github.com/Toblerity/rtree/actions/runs/9866016962), but this seems to be due to the wrong workflow name registered with PyPI. This is fixed for the next round, hopefully!
