### ISSUE TITLE
Integration with Hickle

### ISSUE THREAD

**Issue by brendancol** [Toblerity/rtree#39]
Hey Toblerity,
I'm investigating a library called hickle which allows you to use hdf5 to store objects. https://github.com/telegraphic/hickle
I was trying to get this going and store rtrees inside of HDF for the compression options. Any first impressions of this?  Do you think its as easy as adding an additional import statement and using hickle on index.dumps() & index.loads()?  Any thoughts would be appreciated.

**Comment by hobu** [comment]
Please ask these types of questions on the mailing list.

http://lists.gispython.org/mailman/listinfo/community

In short, I think you might want to implement "custom storage" for HDF5. It should be possible, but it would be some work.
