### ISSUE TITLE
Seg Fault when loading many shapefiles into single rtree

### ISSUE THREAD

**Issue by brendancol** [Toblerity/rtree#40]
Scenario: 
- loading about 15 million polygons into rtree which are spread over about 60 shapefiles.
- I'm using the generator style insert
- about 2 million polygons in, inserts slow dramatically then segmentation faults.
- I'm main guess is that I am running out of memory
- Am I abusing rtree?  Is there a way to flush to disk every so often?

Thanks

**Comment by brendancol** [comment]
def rtree_from_directory(shp_directory, fields, output_rtree_path, pattern='*.shp'):

    for f in glob.glob(output_rtree_path + "*"):
        os.remove(f)

        def feature_gen():
            shps = glob.glob(os.path.join(shp_directory, pattern))
            count = 0
            for shapefile in shps:
                with fiona.open(shapefile) as input_features:
                    for feature in progress.bar(input_features):
                        count += 1
                        attributes = {}
                        attributes['geom'] = feature['geometry']
                        attributes.update({k:v for k,v in feature['properties'].items() if k in fields})
                        yield (count, shape(attributes['geom']).bounds, attributes)
 
    rtree_index = Rtree(output_rtree_path, feature_gen())

**Comment by hobu** [comment]
In the latest libspatialindex and latest Rtree, there is now a `flush()` method, but it really is for finalizing the index. It shouldn't blow up as you're inserting stuff.

The Cloudant guys insert many more than 15 mil entries into the index, so I'm confident it's probably not libspatialindex's fault.

Is there any chance you can do the following?

a) build/install a debug build of libspatialindex
b) run your command under gdb
c) get a stack trace

**Comment by brendancol** [comment]
I simply ran out of RAM.  I found a machine with a bit more juice and it finished just fine.  Thanks for your help.

**Comment by hobu** [comment]
Ok. It would be nice to fall over more gracefully in that case, but it's hard to determine the malloc that fails and capture it cleanly and report back to Python when you are out of memory.
