### ISSUE TITLE
Adding compression to rtree attribute objects

### ISSUE THREAD

**Issue by brendancol** [Toblerity/rtree#41]
Hey is this of any interest to submit back as a pull request?

    import zlib

    from rtree import Rtree

    class CompressedRtree(Rtree):
        '''
        adds zlib compression to rtree
        '''

        def __init__(self, *args, **kwargs):
            Rtree.__init__(self, *args, **kwargs)

        def dumps(self, obj):
            result = super(CompressedRtree, self).dumps(obj)
            return zlib.compress(result)

        def loads(self, string):
            return super(CompressedRtree, self).loads(zlib.decompress(string))

**Comment by hobu** [comment]
Sure. Do the files compress that well?

**Comment by brendancol** [comment]
Since I was writing polygons into the rtree attributes for easy .contains() after running .intersection(), the size of my .dat file was bloated... 15million polygons was about 60GB on disk.  I added zlib and it brought disk size down to 14GB. So far I have noticed too much of a performance hit, but still need to benchmark.

**Comment by hobu** [comment]
> On Jan 22, 2015, at 11:40 AM, brendancol <notifications@github.com> wrote:
> 
> Since I was writing polygons into the rtree attributes for easy .contains() after running .intersection(), the size of my .dat file was bloated...

The rtree isn't really a database though. It is very sensitive to page size and tree parameters in that case. I think you would have quicker access using some sort of key/value store and then mapping that back to your index entries than trying to store serialized polygons inside the rtree.

> 15million polygons was about 60GB on disk. I added zlib and it brought disk size down to 14GB. So far I have noticed too much of a performance hit, but still need to benchmark.

Can I ask what dataset is 15 million polygons?

**Comment by brendancol** [comment]
I took all US census blocks and split them into pieces with each piece having no greater than 250 vertices.  it may actually be more than 15M features.  That is a good point about the key/value store.  I'm currently using Berkeley DB to store the polygon attributes, but not geometry.  In conjunction with pandas and shapely, I'm applying this function to a dataframe to do intersection. Note that the row argument is a row from a pandas dataframe which has a 'geometry' field:

    def first_intersection_func(rtree_object, db_object, id_field):
        def runner(row):
            point = row['geometry']
            hits = list(rtree_object.intersection((point.x,point.y,point.x,point.y), objects=True))
            for h in hits:
                obj = h.object
                if shape(obj['geom']).contains(point):
                    id_value = str(obj[id_field])
                    attrs = db_object.get(id_value)
                    return pandas.Series(json.loads(attrs))
            return None
        return runner

So I am having to do a lookup in the k/v store anyway, so maybe better just to store full polygons in bsddb.  With the above function, what pagesize tree issues do you think i will run into?

**Comment by hobu** [comment]
If your polygons are widely varying in size, it's hard to estimate how big your page size(s) should be. If they're big enough to cover all polys, you'll waste tons of space. If they're too small, you'll spend all your time dividing up and paging.

I would probably store your data as WKB or https://github.com/mapbox/geobuf with a key that maps to your bounds and index entry in the rtree. Low parsing overhead, no worry about custom page size calculations in a storage type that's totally custom (Rtree), and you can send the geoms on down the line to JavaScript or whatever and it can just consume it.

**Comment by brendancol** [comment]
Awesome! thanks for the suggestions.  I didn't know about geobuf.  I will try it out and will also try to ween myself off using rtree as a db.
