### ISSUE TITLE
Install Rtree for phyton on Windows 7

### ISSUE THREAD

**Issue by ernapiantari** [Toblerity/rtree#43]
Help. I have problem when instal Rtree on my windows.
I used cmd for install it.
But it's seem cannot found spatialindex_c.dll
Actually, i have spatialindex_c-64.dll
what sholud i do with it?

this is what i have done:
C:\Python27\Scripts\easy_install.exe Rtree
Best match: Rtree 0.8.2
Downloading https://pypi.python.org/packages/source/R/Rtree/Rtree-0.8.2.tar.gz#md5=4ba7276cbd4c51b373068004ae864d3
Processing Rtree-0.8.2.tar.gz
Writing c:\users.....\Rtree-0.8.02\setup.cfg
Running Rtree-0.8.2\setup.py -q dbist_egg --dist-dir ......
error: could not find or load spatialindex_c.dll

And I tried to download Rtree-0.8.2 and install it offline too, but stiil could not find or load spatialindex_c.dll.

**Comment by scw** [comment]
It doesn't look like the most recent builds of Rtree have windows binaries generated for them, however you can still install the 0.7.0 version by specifying the release:

    easy_install Rtree=0.7.0

Worked fine for me on x64 Win7.

**Comment by ernapiantari** [comment]
Thank you, it's work very well

**Comment by ernapiantari** [comment]
@scw  please...
 I stiil have problem when installation there are warning
WARNING : can't process DATA/DLLs/spatialindex.dll
WARNING : can't process DATA/DLLs/spatialindex_c.dll

**Comment by Felix-neko** [comment]
Eh, I still have the same problem...
Oy vey...

**Comment by scw** [comment]
Hi @Felix-neko, what version of Rtree are you attempting to install, and on what version of Python? Could you describe your environment and the error you receive?

**Comment by Felix-neko** [comment]
Windows 7x64, Python 2.7, rtree 0.8.3

**Comment by scw** [comment]
The issue is that Rtree expects that you have libspatialindex installed. You can download a copy from their [archive](), for Python 2.7 x64 you'd want the x64 VS2008 version. The simpler solution is to use the recommended version on PyPI, [Christoph Golkhe's release](http://www.lfd.uci.edu/~gohlke/pythonlibs/#rtree).

**Comment by HichamZouarhi** [comment]
I had the same problem and solved it by changing the core.py file in Rtree in

> C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\rtree\core.py

and changed this line :

`rt = _load_library('spatialindex_c.dll', ctypes.cdll.LoadLibrary)`
by this :

`rt = _load_library('spatialindex_c-64.dll', ctypes.cdll.LoadLibrary)`

**Comment by anyongjin** [comment]
download rtree whl file from
https://www.lfd.uci.edu/~gohlke/pythonlibs/#rtree
and install with "pip install "
