### ISSUE TITLE
Error in "IndexProperty_GetOverwrite": Property IndexIdentifier was empty

### ISSUE THREAD

**Issue by marfago** [Toblerity/rtree#47]
Could anyone explain this error?
Thank you in advance.
M@rco

2015-04-10 12:41:17 ERROR Zope.SiteErrorLog 1428662477.860.832295083576 
Traceback (innermost last):
...........
  Module Products.LinguaPlone.patches, line 34, in searchResults
  Module Products.CMFPlone.CatalogTool, line 393, in searchResults
  Module Products.ZCatalog.ZCatalog, line 604, in searchResults
  Module Products.ZCatalog.Catalog, line 925, in searchResults
  Module Products.ZCatalog.Catalog, line 547, in search
  Module collective.geo.index.geometryindex, line 169, in _apply_index
  Module collective.geo.index.index, line 69, in rtree
  Module rtree.index, line 211, in __init__
  Module rtree.index, line 985, in get_overwrite
  Module rtree.core, line 42, in check_value
RTreeError: Error in "IndexProperty_GetOverwrite": Property IndexIdentifier was empty

**Comment by hobu** [comment]
I have no idea why the IndexIndentify is reporting empty. There must be something wrong with the IndexPropertyH that is being returned. Possibly it is a bad copy. As I mentioned in #46, please try the latest libspatialindex if you could.

**Comment by marfago** [comment]
I tried lastest revision from github but still getting some errors

Exception rtree.core.RTreeError: RTreeError('Error in "IndexProperty_Destroy": Property IndexIdentifier was empty',) in <bound method PropertyHandle.__del__ of <rtree.index.PropertyHandle object at 0x7ffa1442a910>> ignored

I noticed that the errors do not occur (or occur much lesser) if the index is created with standard settings.
In my project I have different settings like this:

settings = Property()
settings.leaf_capacity = 10000
settings.dimension = 2
return FastRtree(self._basepath, properties = settings)

**Comment by hobu** [comment]
Related to ongoing multithreading issue https://github.com/Toblerity/rtree/issues/53
