### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by christophlingg** [Toblerity/rtree#53]
Thanks for providing RTree for Python!

I was wondering if rtree can be used in a multithreaded context?

**Comment by shongololo** [comment]
+1

**Comment by marfago** [comment]
Actually seems it is not possible. At least with recent versions.

https://github.com/libspatialindex/libspatialindex/issues/71

**Comment by hobu** [comment]
libspatialindex is not threadsafe and Rtree does not do thread safety. It is something that could be done, but it would take a lot of meticulous work to achieve.

**Comment by christophlingg** [comment]
Ok I can comprehend that concurrent writing and reading may cause problems, but are read-only accesses safe?

**Comment by marfago** [comment]
In my experience it seems it is not.
In a project I use https://github.com/collective/collective.geo.index, wich is based on RTree. For each search it instantiates a new instance of RTree and now and then it crashes with segmentation fault. I solved this issue moving the rtree to a global variable (just one instance). Not sure it can help.

**Comment by christophlingg** [comment]
That's strange because I am using accessing one rtree from multiple threads, and so far i did not encounter any problems.

**Comment by snorfalorpagus** [comment]
@christophlingg Race conditions can be like that. It may be that certain issues are only triggered under high(er) loads.

**Comment by hobu** [comment]
> Ok I can comprehend that concurrent writing and reading may cause problems, but are read-only accesses safe?

No. libspatialindex, especially as used through the C API like Rtree does, is not thread safe. If it is working for you, it is most likely due to luck.

**Comment by christophlingg** [comment]
Now I know I need to fix something ;-) Thanks to your feedback this I can do this before it crashes!

**Comment by hobu** [comment]
The most pressing issue is probably the one described in libspatialindex/libspatialindex#71 especially in regards to the C API.

If you put some aggressive locking around things in python land, you are likely to be reasonably protected. The issues most likely manifest themselves in regard to error messages, and the error stack of the C API of libspatialindex not being protected in any way.

**Comment by marfago** [comment]
I'm working with a single thread instance of the index, but it daily crashes!
Can anyone suggest what exactly should be "protected" in python?

**Comment by hobu** [comment]
> Can anyone suggest what exactly should be "protected" in python?

Protect any access you do to libspatialindex with a mutex and lock accordingly.

**Comment by marfago** [comment]
@hobu :Adding mutex or lock did not work for me. Moreover, also using different processes working on the same index file ends up in segmentation fault.

**Comment by hobu** [comment]
libspatialindex has a thread safety issue. Someone needs to develop a clear case that demonstrates the issue so it can be resolved.
