### ISSUE TITLE
get the points in same coordinates

### ISSUE THREAD

**Issue by titoconte** [Toblerity/rtree#55]
is it possible to get the points exacly in the same coordinate of the query input (not the nearest)?

**Comment by hobu** [comment]
I'm not sure what you mean. If you need to preserve some kind of ordering, you will have to do that external to the boxes as they are inserted into the index. They are purposefully reordered to allow accelerated access.

**Comment by titoconte** [comment]
I needed to find what square was closed to my reference square.

I solved use rtree mixed with kdtree.
