### ISSUE TITLE
test_stream_input is failing

### ISSUE THREAD

**Issue by ocefpaf** [Toblerity/rtree#59]
I am trying to build [`rtree` with conda](https://github.com/ioos/conda-recipes/tree/master/rtree) and make it pass all the tests but the [`test_stream_input()`](https://github.com/Toblerity/rtree/blob/master/tests/test_index.py#L10-L15) is failing.

Instead of `[0, 4, 16, 27, 35, 40, 47, 50, 76, 80]` the test is returning a list with all zeros.  I am not familiar with rtree's code, but it seems that the zeros are coming from [`py_next_item`](https://github.com/Toblerity/rtree/blob/master/rtree/index.py#L685-L722).

**Comment by ocefpaf** [comment]
This issue is similar to #48, but downgrading `libspatialindex` to 1.7.0 (build from source, not the one available for Ubuntu) did not fix the issue.

**Comment by vmora** [comment]
From the description, this looks like a duplicate of #71.

**Comment by ocefpaf** [comment]
Since this is older I would say #71 is a dup of this one ;-)

But I am closing this b/c the discussion there gas evolved while this issue remains ignored :-(
