### ISSUE TITLE
How to use stream loading and disk storage together?

### ISSUE THREAD

**Issue by BrenBarn** [Toblerity/rtree#60]
As far as I can tell from the documentation and the code, Rtree lets you either specify a filename for disk-based index, or a stream for stream loading.  But how can I do both?  What if I want a disk-based index which is populated by reading from a stream?

**Comment by daradib** [comment]
Try passing both, with the filename as the first argument and stream as the second (see [source](/Toblerity/rtree/blob/master/rtree/index.py#L191)), e.g.,

    index.Index(filename, stream)

**Comment by BrenBarn** [comment]
Yeah, I figured that out eventually.  However, that is inconsistent with [the documentation](http://toblerity.org/rtree/class.html) which refers to "the first argument" being *either* a filename *or* a stream.  It would be good to clarify that `filename` and `stream` are not mutually exclusive.

**Comment by hobu** [comment]
> refers to "the first argument" being either a filename or a stream.

Please make a PR that updates the documentation to make this more clear.
