### ISSUE TITLE
encode - decode bytes

### ISSUE THREAD

**Issue by capekode** [Toblerity/rtree#62]
hi, 
i'm trying to use rtree in python3. i'm using the version installed by:  

   pip3 install rtree

on my ubuntu 15.04. 

creating a (disk stored) index, i got an error about wrong type in set_dat_extension. had a look at the code and noticed that, at least in my version, there is:

        v = value.encode('utf-8')
        return core.rt.IndexProperty_SetFileNameExtensionDat(self.handle, value)

so, you encode the string into bytes but after you still pass the original string to the c function. i fixed this, here as well as in set_idx_extension, passing v instead of value. i also modified get_idx_extension and get_dat_extension adding a .decode('utf-8') in order to return strings and not bytes (without this step there were other errors about adding bytes to strings...). that solved the problem. 
i guess you'll probably want to reflect the fix on your sources. 

and thank you for the great job done so far!

**Comment by hobu** [comment]
This appears to be fixed in the master branch:

https://github.com/Toblerity/rtree/blob/master/rtree/index.py#L1169

Please reopen the issue if it is still a problem.
