### ISSUE TITLE
bulk loading and ids

### ISSUE THREAD

**Issue by capekode** [Toblerity/rtree#63]
hallo, 
i have the following test code:

    from rtree import index.Index

    def test():
        for i in range(10):
            yield (i,(i,i,i,i),{'i':i})

    idx=Index('/tmp/idxtest',test())
    for i in idx.nearest((0,0,0,0),20,objects=True):
        print( i.id, i.bounds, i.object )

and the output is:

    0 {'i': 0} [0.0, 0.0, 0.0, 0.0]
    0 {'i': 1} [1.0, 1.0, 1.0, 1.0]
    0 {'i': 2} [2.0, 2.0, 2.0, 2.0]
    0 {'i': 3} [3.0, 3.0, 3.0, 3.0]
    0 {'i': 4} [4.0, 4.0, 4.0, 4.0]
    0 {'i': 5} [5.0, 5.0, 5.0, 5.0]
    0 {'i': 6} [6.0, 6.0, 6.0, 6.0]
    0 {'i': 7} [7.0, 7.0, 7.0, 7.0]
    0 {'i': 8} [8.0, 8.0, 8.0, 8.0]
    0 {'i': 9} [9.0, 9.0, 9.0, 9.0]

... all ids are 0! 
i have verified the ids arrive unchanged at least until [here](https://github.com/Toblerity/rtree/blob/master/rtree/index.py#L692), but what happens after is a little too hard to track for me.

**Comment by ocefpaf** [comment]
Same as #59

**Comment by capekode** [comment]
and the same as #48, as i just noticed. 
that one contains a more in depth discussion about this problem, which can be solved simply by installing libstaptialindex 1.7.0. 
i close this issue.
