### ISSUE TITLE
Index does not pickle fully

### ISSUE THREAD

**Issue by megatron-me-uk** [Toblerity/rtree#65]
When pickling and unpickling an Index, not enough information is stored to create a new index. Instead, pointers to the original index are stored. This can cause problems in multiprocess environments (such as pyspark).

Minimal code to reproduce:
```
>>> import rtree
>>> index=rtree.index.Index()
>>> index.insert(1, (1,1,2,2))
>>> index.intersection((1.5,1.5))
<generator object _get_ids at 0x7ffe78c9b780>
>>> list(index.intersection((1.5,1.5)))
[1]
>>> import cPickle
>>> pck=cPickle.dumps(index)
>>> index2=cPickle.loads(pck)
>>> list(index2.intersection((1.5,1.5)))
[1]
>>> pck
"ccopy_reg\n_reconstructor\np1\n(crtree.index\nIndex\np2\nc__builtin__\nobject\np3\nNtRp4\n(dp5\nS'owned'\np6\nI01\nsS'handle'\np7\nI20381712\nsS'properties'\np8\ng1\n(crtree.index\nProperty\np9\ng3\nNtRp10\n(dp11\ng7\nI20354048\nsg6\nI01\nsbsS'interleaved'\np12\nI01\nsb."
>>> del index
>>> 
>>> list(index2.intersection((1.5,1.5)))
Segmentation fault
```

On pyspark this means that an rtree Index cannot be broadcast to the slave nodes. A possible workaround is to create the index separately on each slave node.

Note: I believe this is a separate issue to several highly google-able multithreading issues that produce the same error messages, namely:
```
RTreeError('Error in "IndexProperty_GetDimension": Property Dimension was empty',)
```

**Comment by hobu** [comment]
Has an Index object ever been picklable? I didn't think it was. It would be possible to implement support for it, but you would have to implement a libspatialindex storage backend.
