### ISSUE TITLE
Bulk Stream loading

### ISSUE THREAD

**Issue by soumyami** [Toblerity/rtree#66]
The combination of Rtree 0.8.2 and libspatialindex 1.8.5 works well on Darwin (OS X) with stream loading but it shows error of wrong number of dimensions when using on RHEL 6.5. So I downgraded the libspatialindex to different versions and observed no errors with < 1.8.0. But then, I started getting problems with wrong id's (all zeros) similar to previous issues. 
So, now I downgraded Rtree as well to version 0.8.0 and now everything works well! 

Essentially, stream loading works for me on 0.8.0 + 1.8.0 combination on RHEL 6.5. The usual workarounds work in my case as well, such as using insert method and returning raw objects but they are slow. 

Why is this happening? Are there any optimizations added in the newer versions for both Rtree and libspatialindex?

Thanks

**Comment by ocefpaf** [comment]
Just to xref another issue #59.  And thanks @soumyami for figure out the combinations that work.
