### ISSUE TITLE
Memory leak / garbage collection issue with large objects

### ISSUE THREAD

**Issue by ARF1** [Toblerity/rtree#67]
If one stores a large number of (large-ish) objects (python nested lists) in the RTree, one encounters the following error on Windows and CPython 3.4.4, rtree 0.8.2:

`RTreeError: Error in "Index_CreateWithStream": b'bad allocation'`

Same issue occurs when one does not use stream loading.

My hunch is that the buffer created with `create_string_buffer(...)` in `_serialize(...)` never gets freed.

The only reliable solution I found was to call

```
import gc
gc.collect()
```

in `py_next_item(...)` in `Index._create_idx_from_stream(...)` every once in a while.

**Comment by hobu** [comment]
Valgrind doesn't complain about leaks when we run the tests (which include creation of indexes from streams). I'm not sure we are supposed to be forcing garbage collection like this, but I can't argue with the results. I'm unsure how to proceed.

**Comment by ARF1** [comment]
@hobu To be honest, I cannot remember any more what exactly I was doing.

I vaguely remember however that at some point in the past I had truly perplexing memory leaks with a project. I can no longer remember if this was with rtree or not.

The problem was that I was using IPython `%timeit` to time a loop. However `timeit` disables the garbage collector before beginning its measurement. Thus object created in the loop were never freed.

It could be that the OP was connected to this phenomenon. I cannot be sure though.

I would suggest closing this issue until somebody else can reproduce this issue. Unfortunately I am not using rtree at the moment.
