### ISSUE TITLE
dat_extension & idx_extension cannot be set

### ISSUE THREAD

**Issue by ARF1** [Toblerity/rtree#69]
On
```
Python 3.4.4 |Continuum Analytics, Inc.| (default, Mar  4 2016, 15:23:09) [MSC v
.1600 32 bit (Intel)] on win32
```
the `dat_extension` and `idx_extension` properties cannot be set:
```
Traceback (most recent call last):
  File "C:\Users\ARF1\Documents\Programming\gis\module1.py", line 242, in
<module>
    run(args)
  File "C:\Users\ARF1\Documents\Programming\gis\module1.py", line 138, in
run
    rtree_props.dat_extension = 'rtree_dat'
  File "C:\Anaconda\envs\gis\lib\site-packages\rtree\index.py", line 1056, in se
t_dat_extension
    return core.rt.IndexProperty_SetFileNameExtensionDat(self.handle, value)
ctypes.ArgumentError: argument 2: <class 'TypeError'>: wrong type
Press any key to continue . . .
```

Failed work-arounds:
- `rtree_props.dat_extension = r'rtree_dat'`
- `rtree_props.dat_extension = c_wchar_p('rtree_dat')`
- `rtree_props.dat_extension = c_char_p(b'rtree_dat')`

**Comment by hobu** [comment]
This is tested in the tests. https://github.com/Toblerity/rtree/blob/master/tests/properties.txt#L241  You are going to have to provide more code that demonstrates the scenario. Please reopen if this is still an issue.
