### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by QuLogic** [Toblerity/rtree#84]
http://toblerity.github.com/rtree/ (in the info here) redirects to http://toblerity.org/rtree/ which is the documentation for 0.7.0, when there have been 4 releases after that.

**Comment by Juanlu001** [comment]
Perhaps we can have it in ReadTheDocs, as fiona, shapely and rasterio? Would you accept a pull request doing that?

**Comment by sgillies** [comment]
@Juanlu001 yes, indeed!
