### ISSUE TITLE
Cannot install rtree with PyInstaller (spatialindex library is not copied)

### ISSUE THREAD

**Issue by Felix-neko** [Toblerity/rtree#88]
I have a Python script that use `rtree`. I want to build an exe file with it and its dependencies via PyInstaller. 

Alas, when the exe is built, the 

Here is a minimal example of script `rtree_demo.py` using `rtree` (taken from your tutorial):
```
import rtree
from rtree import index

if __name__ == "__main__":
    idx = index.Index()
    left, bottom, right, top = (0.0, 0.0, 1.0, 1.0)
    idx.insert(0, (left, bottom, right, top))
    print(list(idx.intersection((1.0, 1.0, 2.0, 2.0))))
    print(list(idx.intersection((1.0000001, 1.0000001, 2.0, 2.0))))
```

I tried to build it with PyInstaller:

`pyinstaller.exe --onedir rtree_demo.py`

When it was built, I tried to run `dist/rtree_demo/rtree_demo.exe`. Alas, it said me:

```
OSError: could not find or load spatialindex_c.dll
Failed to execute script rtree_demo
```

Cannot you fix it?

**Comment by scw** [comment]
Rtree doesn't explicitly include the DLL. You can either add it manually into the PyInstaller build by declaring it has an additional dependency, or more simply use a version which does include libspatialindex explicitly. [Christoph Golkhe's release](http://www.lfd.uci.edu/~gohlke/pythonlibs/#rtree) does so, as does the related Conda package.

**Comment by GISConsortium** [comment]
Actually, I am new to python stuff, I have installed Rtree from [Christoph Golkhe's release](https://www.lfd.uci.edu/~gohlke/pythonlibs/#rtree) but now I don't how to add the dependency for libspatialindex.

**Comment by scw** [comment]
@GISConsortium libspatialindex is already included in his build.

**Comment by ericeasthope** [comment]
It seems like this continues to be an issue (currently on v0.9.1, as using v0.9.2 or greater fails during installation with `pipenv`). The recommended solution, that is to use Christoph Golkhe's release, is limited to Windows users. This excludes a very large user base (i.e. all *nix users?). I'm on a Mac running 10.15 Catalina.

I've gone further to explicitly include the necessary binaries through the Pyinstaller spec file, but the problem remains: executables frozen through Pyinstaller simply won't see `libspatialindex_c`.

To reproduce I'm using

```python
from ctypes.util import find_library
find_library('libspatialindex_c') # => None
from rtree import Rtree # => OSError: could not find or load ...
```

within the main Pyinstaller script. Pipenv is managing my virtual environment.

At the moment this is a breaking issue and prevents standalone Python executables that rely on Rtree from being used in cross-platform production applications. e.g. On macOS, users must rely on `brew install spatialindex` (as described [here](https://github.com/gboeing/osmnx/issues/45)). This defeats the purpose of using Pyinstaller in the first place.

What can be done from here? Can I help?

**Comment by pakiradhaan** [comment]
@ericeasthope I was facing the same issue as you, running on mac and having problems with spacialindex library dependancy within rtree (implicitely call by geopandas).

Once you have installed libspatialindex via homebrew on your computer, the computer that needs to generate the executable, you just have to tell pyinstaller to add these binaries also and where they are located :

`a.binaries = a.binaries + [('libspatialindex_c.6.1.1.dylib', '/usr/local/Cellar/spatialindex/1.9.3/lib/libspatialindex_c.6.1.1.dylib','BINARY')]
a.binaries = a.binaries + [('libspatialindex_c.6.dylib', '/usr/local/Cellar/spatialindex/1.9.3/lib/libspatialindex_c.6.dylib','BINARY')]
a.binaries = a.binaries + [('libspatialindex_c.dylib', '/usr/local/Cellar/spatialindex/1.9.3/lib/libspatialindex_c.dylib','BINARY')]
a.binaries = a.binaries + [('libspatialindex.6.1.1.dylib', '/usr/local/Cellar/spatialindex/1.9.3/lib/libspatialindex.6.1.1.dylib','BINARY')]
a.binaries = a.binaries + [('libspatialindex.6.dylib', '/usr/local/Cellar/spatialindex/1.9.3/lib/libspatialindex.6.dylib','BINARY')]
a.binaries = a.binaries + [('libspatialindex.dylib', '/usr/local/Cellar/spatialindex/1.9.3/lib/libspatialindex.dylib','BINARY')]`

Hope it works for you also !

**Comment by timurkanaz** [comment]
Hi everyone! Are there any ways to resolve this problem on Windows?

**Comment by pakiradhaan** [comment]
> Hi everyone! Are there any ways to resolve this problem on Windows?

Did you install Christoph Golkhe's release for rtree ? If so, apparently, it should work without doing anything specific.

The link is in previous comments..

**Comment by timurkanaz** [comment]
> > Hi everyone! Are there any ways to resolve this problem on Windows?
> 
> Did you install Christoph Golkhe's release for rtree ? If so, apparently, it should work without doing anything specific.
> 
> The link is in previous comments..

Yes, I have installed wheel file and now  I have rtree 0.9.4. Maybe I misunderstood what "binary" files are ...  So I  have added .lib files in .spec binaries.

**Comment by reinzor** [comment]
```
binaries = []
if os.name == "nt":
    binaries += collect_dynamic_libs("rtree")
else:
    binaries += [('/lib/x86_64-linux-gnu/libspatialindex*', '.')]
```

worked for me
