### ISSUE TITLE
Index stream error message is unhelpful

### ISSUE THREAD

**Issue by r-barnes** [Toblerity/rtree#89]
I have the following program:

```
import rtree
ridx1 = rtree.index.Index( [(0,(0,0,10,10))] )
ridx2 = rtree.index.Index( [(0,(0,0,10,10),None)] )
```

Running it gives the following output:

```
>>> import rtree
>>> 
>>> ridx = rtree.index.Index( [(0,(0,0,10,10))] )
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3/dist-packages/rtree/index.py", line 679, in py_next_item
    p_id[0], coordinates, obj = next(stream_iter)
ValueError: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/rtree/index.py", line 246, in __init__
    self.handle = self._create_idx_from_stream(stream)
  File "/usr/lib/python3/dist-packages/rtree/index.py", line 710, in _create_idx_from_stream
    return core.rt.Index_CreateWithStream(self.properties.handle, stream)
  File "/usr/lib/python3/dist-packages/rtree/core.py", line 24, in check_void
    raise RTreeError(msg)
rtree.core.RTreeError: Error in "Index_CreateWithStream": b'IllegalArgumentException: RTree::BulkLoader::bulkLoadUsingSTR: Empty data stream given.'
>>> 
>>> ridx = rtree.index.Index( [(0,(0,0,10,10),None)] )
>>> 
```

Note that the key message to me, the user, is `Empty data stream given.`

In reality, the issue is that I haven't included a `None` object as part of the input tuple. It would be nice if this issue was detected and a more helpful message given to the user.

**Comment by brockhicks** [comment]
cc @kuanb

**Comment by kuanb** [comment]
I'm encountering this situation right now, as well. If I understand what `rtree` is looking for, then I don't think that, in your case, it was that `None` was absent, but that there was missing _any_ value for that 3rd position in the tuple.

I'm getting the same error and I _am_ including that 3rd parameter. I'm totally confused as to what is causing this. I wonder if the bounds having negative values could be in any way playing a role?

Here's what the output of a print statement on a `for` loop iterating over `stream` looks like for me:
```python
(0, (281473.8384324173, -422731.216320558, 289531.2399623143, -419992.0005550077), None)
(1, (278377.2483709769, -415432.4581559254, 279786.94952721725, -414811.45352902496), None)
(2, (256786.5875656332, -400326.51186657185, 258338.59741178015, -399619.61350248987), None)
(3, (281222.9056414375, -411317.9897525087, 281645.4770052117, -410564.033803293), None)
(4, (251378.12023050044, -389153.48450573254, 252258.80184262068, -386909.02386022685), None)
(5, (256141.783696895, -414343.1036637933, 256633.21048439894, -412962.50522225816), None)
(6, (253555.11683555823, -398251.4298103424, 253690.85107234033, -398045.04127232265), None)
(7, (219307.47555488907, -405733.56742053153, 219716.25389953415, -405327.6065815557), None)
(8, (261501.75012612535, -415113.97786365775, 264624.1711555223, -412652.11804838944), None)
```

**Comment by r-barnes** [comment]
I think I was using negative bounds (I was using global Mercator-projected data) and adding None fixed thinks for me. :-/

**Comment by GISConsortium** [comment]
I am facing the same issue, but errors I am getting are weird, Here is my code.

import rtree
ridx = rtree.index.Index( [(0,(0,0,10,10),None)] )

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 313, in 'calling callback function'
  File "C:\Python27\lib\site-packages\rtree\index.py", line 717, in py_next_item
    p_dimension[0] = dimension
ValueError: NULL pointer access
Traceback (most recent call last):
  Python Shell, prompt 3, line 1
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 264, in __init__
    self.handle = self._create_idx_from_stream(stream)
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 728, in _create_idx_from_stream
    return IndexStreamHandle(self.properties.handle, stream)
  File "C:\Python27\Lib\site-packages\rtree\index.py", line 854, in __init__
    self._ptr = self._create(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\rtree\core.py", line 28, in check_void
    raise RTreeError(msg)
rtree.core.RTreeError: Error in "Index_CreateWithStream": IllegalArgumentException: RTree::BulkLoader::bulkLoadUsingSTR: Empty data stream given.

**Comment by nchidsey** [comment]
For what it's worth, I think the original post is a manifestation of #80.  The `ValueError` is printed to stderr but otherwise ignored.  And the "Empty data stream given" exception is _slightly_ unrelated, occurring because no items were successfully inserted before the end.

**Comment by TryHarder01** [comment]
@GISConsortium I was able to successfully run your code with Python 3.6 and Rtree 0.8.3

```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rtree
>>> ridx = rtree.index.Index( [(0,(0,0,10,10),None)] )
>>> 
>>> 

```

**Comment by hobu** [comment]
https://github.com/Toblerity/rtree/commit/44ad21aecd3f7b49314b9be12f3334d8bae7e827#diff-d81684ea57a4576f3ff7720dd43a08d1 hopefully fixes this issue with the exception. Please report otherwise.

**Comment by mariaculman18** [comment]
Hi @hobu, I just updated the Rtree package from 0.8.3 to 0.9.0, and the problem has changed from `'IndexStreamHandle' object has no attribute '_ptr'` to `AttributeError: 'Index' object has no attribute 'handle'`.

Any idea why it is happening? 

Thanks!

**Comment by hobu** [comment]
0.9.0 is not yet released. Can you post some example code that demonstrates the issue?

**Comment by mariaculman18** [comment]
I did `pip install git+git://github.com/Toblerity/rtree.git` and that is how I got Rtree 0.9.0

The issue seems to be between Geopandas and Rtree:

```
Traceback (most recent call last):
  File "preannotating_1.py", line 108, in <module>
    PC.crowns_to_polys_smooth(tname, store_las=True)
  File "C:\Users\CULMANFM\AppData\Local\Continuum\anaconda3\envs\PyCrown\lib\site-packages\pycrown-0.2-py3.6-win-amd64.egg\pycrown\pycrown.py", line 881, in crowns_to_polys_smooth
    op='within', how="inner")
  File "C:\Users\CULMANFM\AppData\Local\Continuum\anaconda3\envs\PyCrown\lib\site-packages\geopandas\tools\sjoin.py", line 72, in sjoin
    .apply(lambda x: list(tree_idx.intersection(x))))
  File "C:\Users\CULMANFM\AppData\Local\Continuum\anaconda3\envs\PyCrown\lib\site-packages\pandas\core\series.py", line 3194, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/src/inference.pyx", line 1472, in pandas._libs.lib.map_infer
  File "C:\Users\CULMANFM\AppData\Local\Continuum\anaconda3\envs\PyCrown\lib\site-packages\geopandas\tools\sjoin.py", line 72, in <lambda>
    .apply(lambda x: list(tree_idx.intersection(x))))
  File "C:\Users\CULMANFM\AppData\Local\Continuum\anaconda3\envs\PyCrown\lib\site-packages\rtree\index.py", line 695, in intersection
    core.rt.Index_Intersects_id(self.handle,
AttributeError: 'Index' object has no attribute 'handle'
``` 

> 0.9.0 is not yet released. Can you post some example code that demonstrates the issue?
> […](#)
> On Nov 22, 2019, at 5:27 AM, mariaculman18 ***@***.***> wrote: ﻿ Hi @hobu, I just updated the Rtree package from 0.8.3 to 0.9.0, and the problem has changed from 'IndexStreamHandle' object has no attribute '_ptr' to AttributeError: 'Index' object has no attribute 'handle'. Any idea why it is happening? Thanks! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hobu** [comment]
Ok. Master isn’t quite ready for production yet :smile:

I know what this is related to and I’ll try to make a patch that cures it.

**Comment by mariaculman18** [comment]
Hi @hobu, sorry to bother you. I found that my error is related to my data source.

Thank you for your time!

> Ok. Master isn’t quite ready for production yet 😄 I know what this is related to and I’ll try to make a patch that cures it.
> […](#)
> On Nov 24, 2019, at 5:22 AM, mariaculman18 ***@***.***> wrote: ﻿ I did pip install git+git://github.com/Toblerity/rtree.git and that is how I got Rtree 0.9.0 The issue seems to be between Geopandas and Rtree: Traceback (most recent call last): File "preannotating_1.py", line 108, in <module> PC.crowns_to_polys_smooth(tname, store_las=True) File "C:\Users\CULMANFM\AppData\Local\Continuum\anaconda3\envs\PyCrown\lib\site-packages\pycrown-0.2-py3.6-win-amd64.egg\pycrown\pycrown.py", line 881, in crowns_to_polys_smooth op='within', how="inner") File "C:\Users\CULMANFM\AppData\Local\Continuum\anaconda3\envs\PyCrown\lib\site-packages\geopandas\tools\sjoin.py", line 72, in sjoin .apply(lambda x: list(tree_idx.intersection(x)))) File "C:\Users\CULMANFM\AppData\Local\Continuum\anaconda3\envs\PyCrown\lib\site-packages\pandas\core\series.py", line 3194, in apply mapped = lib.map_infer(values, f, convert=convert_dtype) File "pandas/_libs/src/inference.pyx", line 1472, in pandas._libs.lib.map_infer File "C:\Users\CULMANFM\AppData\Local\Continuum\anaconda3\envs\PyCrown\lib\site-packages\geopandas\tools\sjoin.py", line 72, in <lambda> .apply(lambda x: list(tree_idx.intersection(x)))) File "C:\Users\CULMANFM\AppData\Local\Continuum\anaconda3\envs\PyCrown\lib\site-packages\rtree\index.py", line 695, in intersection core.rt.Index_Intersects_id(self.handle, AttributeError: 'Index' object has no attribute 'handle' 0.9.0 is not yet released. Can you post some example code that demonstrates the issue? … On Nov 22, 2019, at 5:27 AM, mariaculman18 @.***> wrote: ﻿ Hi @hobu, I just updated the Rtree package from 0.8.3 to 0.9.0, and the problem has changed from 'IndexStreamHandle' object has no attribute '_ptr' to AttributeError: 'Index' object has no attribute 'handle'. Any idea why it is happening? Thanks! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
