### ISSUE TITLE
AttributeError: 'function' object has no attribute 'Index'

### ISSUE THREAD

**Issue by nafis042** [Toblerity/rtree#91]
from rtree import index

def read(request):
    idx = index.Index()
    return HttpResponse("")

getting this error : AttributeError: 'function' object has no attribute 'Index'
I am running on windows and downloaded the whl file from http://www.lfd.uci.edu/~gohlke/pythonlibs/#rtree

**Comment by hobu** [comment]
> getting this error : AttributeError: 'function' object has no attribute 'Index' 

You must have some other function called `index`, either defined in the `read()` method or globally. Also, I would suggest using the official wheels which are now available via PyPI. https://pypi.python.org/pypi/Rtree
