### ISSUE TITLE
Nearest Neighbors Order

### ISSUE THREAD

**Issue by SZanlongo** [Toblerity/rtree#99]
Does `nearest` simply return the `k` nearest neighbors (unordered), or do they follow a specific ordering?

I've tried following the implementation myself but haven't figured it out yet.

**Comment by kannes** [comment]
At least in my tests with random coordinates they are returned in growing order of distance. I did not test geometries from within the query window. I don't know in which order multiple index items with the same distances are returned.

Clarification would make a great addition to the docs!
